export const ELEMENTS = [
    {
        "AtomicNumber": "1",
        "Symbol": "H",
        "Name_es": "Hidrógeno",
        "Name_en": "Hydrogen",
        "OxidationStates": "+1, -1",
        "GroupBlock": "Nonmetal",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "1.0080",
        "CPKHexColor": "FFFFFF",
        "ElectronConfiguration": "1s1",
        "Electronegativity": "2.2",
        "AtomicRadius": "120",
        "IonizationEnergy": "13598",
        "ElectronAffinity": "754",
        "StandardState": "Gas",
        "MeltingPoint": "13.81",
        "BoilingPoint": "20.28",
        "Density": "0.00008988",
        "YearDiscovered": "1766"
    },
    {
        "AtomicNumber": "2",
        "Symbol": "He",
        "Name_es": "Helio",
        "Name_en": "Helium",
        "OxidationStates": "0",
        "GroupBlock": "Noble gas",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "4.00260",
        "CPKHexColor": "D9FFFF",
        "ElectronConfiguration": "1s2",
        "Electronegativity": "",
        "AtomicRadius": "140",
        "IonizationEnergy": "24587",
        "ElectronAffinity": "",
        "StandardState": "Gas",
        "MeltingPoint": "0.95",
        "BoilingPoint": "4.22",
        "Density": "0.0001785",
        "YearDiscovered": "1868"
    },
    {
        "AtomicNumber": "3",
        "Symbol": "Li",
        "Name_es": "Litio",
        "Name_en": "Lithium",
        "OxidationStates": "1",
        "GroupBlock": "Alkali metal",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "7.0",
        "CPKHexColor": "CC80FF",
        "ElectronConfiguration": "[He]2s1",
        "Electronegativity": "0.98",
        "AtomicRadius": "182",
        "IonizationEnergy": "5392",
        "ElectronAffinity": "618",
        "StandardState": "Solid",
        "MeltingPoint": "453.65",
        "BoilingPoint": "1615",
        "Density": "534",
        "YearDiscovered": "1817"
    },
    {
        "AtomicNumber": "4",
        "Symbol": "Be",
        "Name_es": "Berilio",
        "Name_en": "Beryllium",
        "OxidationStates": "2",
        "GroupBlock": "Alkaline earth metal",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "9.012183",
        "CPKHexColor": "C2FF00",
        "ElectronConfiguration": "[He]2s2",
        "Electronegativity": "1.57",
        "AtomicRadius": "153",
        "IonizationEnergy": "9323",
        "ElectronAffinity": "",
        "StandardState": "Solid",
        "MeltingPoint": "1560",
        "BoilingPoint": "2744",
        "Density": "1.85",
        "YearDiscovered": "1798"
    },
    {
        "AtomicNumber": "5",
        "Symbol": "B",
        "Name_es": "Boro",
        "Name_en": "Boron",
        "OxidationStates": "3",
        "GroupBlock": "Metalloid",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "10.81",
        "CPKHexColor": "FFB5B5",
        "ElectronConfiguration": "[He]2s2 2p1",
        "Electronegativity": "2.04",
        "AtomicRadius": "192",
        "IonizationEnergy": "8298",
        "ElectronAffinity": "277",
        "StandardState": "Solid",
        "MeltingPoint": "2348",
        "BoilingPoint": "4273",
        "Density": "2.37",
        "YearDiscovered": "1808"
    },
    {
        "AtomicNumber": "6",
        "Symbol": "C",
        "Name_es": "Carbono",
        "Name_en": "Carbon",
        "OxidationStates": "+4, +2, -4",
        "GroupBlock": "Nonmetal",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "12011",
        "CPKHexColor": "909090",
        "ElectronConfiguration": "[He]2s2 2p2",
        "Electronegativity": "2.55",
        "AtomicRadius": "170",
        "IonizationEnergy": "11260",
        "ElectronAffinity": "1263",
        "StandardState": "Solid",
        "MeltingPoint": "3823",
        "BoilingPoint": "4098",
        "Density": "2.2670",
        "YearDiscovered": "Ancient"
    },
    {
        "AtomicNumber": "7",
        "Symbol": "N",
        "Name_es": "Nitrógeno",
        "Name_en": "Nitrogen",
        "OxidationStates": "+5, +4, +3, +2, +1, -1, -2, -3",
        "GroupBlock": "Nonmetal",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "14007",
        "CPKHexColor": "3050F8",
        "ElectronConfiguration": "[He] 2s2 2p3",
        "Electronegativity": "3.04",
        "AtomicRadius": "155",
        "IonizationEnergy": "14534",
        "ElectronAffinity": "",
        "StandardState": "Gas",
        "MeltingPoint": "63.15",
        "BoilingPoint": "77.36",
        "Density": "0.0012506",
        "YearDiscovered": "1772"
    },
    {
        "AtomicNumber": "8",
        "Symbol": "O",
        "Name_es": "Oxígeno",
        "Name_en": "Oxygen",
        "OxidationStates": "-2",
        "GroupBlock": "Nonmetal",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "15999",
        "CPKHexColor": "FF0D0D",
        "ElectronConfiguration": "[He]2s2 2p4",
        "Electronegativity": "3.44",
        "AtomicRadius": "152",
        "IonizationEnergy": "13618",
        "ElectronAffinity": "1461",
        "StandardState": "Gas",
        "MeltingPoint": "54.36",
        "BoilingPoint": "90.2",
        "Density": "0.001429",
        "YearDiscovered": "1774"
    },
    {
        "AtomicNumber": "9",
        "Symbol": "F",
        "Name_es": "Flúor",
        "Name_en": "Fluorine",
        "OxidationStates": "-1",
        "GroupBlock": "Halogen",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "18.99840316",
        "CPKHexColor": "9E+051",
        "ElectronConfiguration": "[He]2s2 2p5",
        "Electronegativity": "3.98",
        "AtomicRadius": "135",
        "IonizationEnergy": "17423",
        "ElectronAffinity": "3339",
        "StandardState": "Gas",
        "MeltingPoint": "53.53",
        "BoilingPoint": "85.03",
        "Density": "0.001696",
        "YearDiscovered": "1670"
    },
    {
        "AtomicNumber": "10",
        "Symbol": "Ne",
        "Name_es": "Neón",
        "Name_en": "Neon",
        "OxidationStates": "0",
        "GroupBlock": "Noble gas",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "20180",
        "CPKHexColor": "B3E3F5",
        "ElectronConfiguration": "[He]2s2 2p6",
        "Electronegativity": "",
        "AtomicRadius": "154",
        "IonizationEnergy": "21565",
        "ElectronAffinity": "",
        "StandardState": "Gas",
        "MeltingPoint": "24.56",
        "BoilingPoint": "27.07",
        "Density": "0.0008999",
        "YearDiscovered": "1898"
    },
    {
        "AtomicNumber": "11",
        "Symbol": "Na",
        "Name_es": "Sodio",
        "Name_en": "Sodium",
        "OxidationStates": "1",
        "GroupBlock": "Alkali metal",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "22.9897693",
        "CPKHexColor": "AB5CF2",
        "ElectronConfiguration": "[Ne]3s1",
        "Electronegativity": "0.93",
        "AtomicRadius": "227",
        "IonizationEnergy": "5139",
        "ElectronAffinity": "548",
        "StandardState": "Solid",
        "MeltingPoint": "370.95",
        "BoilingPoint": "1156",
        "Density": "0.97",
        "YearDiscovered": "1807"
    },
    {
        "AtomicNumber": "12",
        "Symbol": "Mg",
        "Name_es": "Magnesio",
        "Name_en": "Magnesium",
        "OxidationStates": "2",
        "GroupBlock": "Alkaline earth metal",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "24305",
        "CPKHexColor": "8AFF00",
        "ElectronConfiguration": "[Ne]3s2",
        "Electronegativity": "1.31",
        "AtomicRadius": "173",
        "IonizationEnergy": "7646",
        "ElectronAffinity": "",
        "StandardState": "Solid",
        "MeltingPoint": "923",
        "BoilingPoint": "1363",
        "Density": "1.74",
        "YearDiscovered": "1808"
    },
    {
        "AtomicNumber": "13",
        "Symbol": "Al",
        "Name_es": "Aluminio",
        "Name_en": "Aluminum",
        "OxidationStates": "3",
        "GroupBlock": "Post-transition metal",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "26.981538",
        "CPKHexColor": "BFA6A6",
        "ElectronConfiguration": "[Ne]3s2 3p1",
        "Electronegativity": "1.61",
        "AtomicRadius": "184",
        "IonizationEnergy": "5986",
        "ElectronAffinity": "441",
        "StandardState": "Solid",
        "MeltingPoint": "933437",
        "BoilingPoint": "2792",
        "Density": "2.70",
        "YearDiscovered": "Ancient"
    },
    {
        "AtomicNumber": "14",
        "Symbol": "Si",
        "Name_es": "Silicio",
        "Name_en": "Silicon",
        "OxidationStates": "+4, +2, -4",
        "GroupBlock": "Metalloid",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "28085",
        "CPKHexColor": "F0C8A0",
        "ElectronConfiguration": "[Ne]3s2 3p2",
        "Electronegativity": "1.9",
        "AtomicRadius": "210",
        "IonizationEnergy": "8152",
        "ElectronAffinity": "1385",
        "StandardState": "Solid",
        "MeltingPoint": "1687",
        "BoilingPoint": "3538",
        "Density": "2.3296",
        "YearDiscovered": "1854"
    },
    {
        "AtomicNumber": "15",
        "Symbol": "P",
        "Name_es": "Fósforo",
        "Name_en": "Phosphorus",
        "OxidationStates": "+5, +3, -3",
        "GroupBlock": "Nonmetal",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "30.97376200",
        "CPKHexColor": "FF8000",
        "ElectronConfiguration": "[Ne]3s2 3p3",
        "Electronegativity": "2.19",
        "AtomicRadius": "180",
        "IonizationEnergy": "10487",
        "ElectronAffinity": "746",
        "StandardState": "Solid",
        "MeltingPoint": "317.3",
        "BoilingPoint": "553.65",
        "Density": "1.82",
        "YearDiscovered": "1669"
    },
    {
        "AtomicNumber": "16",
        "Symbol": "S",
        "Name_es": "Azufre",
        "Name_en": "Sulfur",
        "OxidationStates": "+6, +4, -2",
        "GroupBlock": "Nonmetal",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "32.07",
        "CPKHexColor": "FFFF30",
        "ElectronConfiguration": "[Ne]3s2 3p4",
        "Electronegativity": "2.58",
        "AtomicRadius": "180",
        "IonizationEnergy": "10360",
        "ElectronAffinity": "2077",
        "StandardState": "Solid",
        "MeltingPoint": "388.36",
        "BoilingPoint": "717.75",
        "Density": "2067",
        "YearDiscovered": "Ancient"
    },
    {
        "AtomicNumber": "17",
        "Symbol": "Cl",
        "Name_es": "Cloro",
        "Name_en": "Chlorine",
        "OxidationStates": "+7, +5, +1, -1",
        "GroupBlock": "Halogen",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "35.45",
        "CPKHexColor": "1FF01F",
        "ElectronConfiguration": "[Ne]3s2 3p5",
        "Electronegativity": "3.16",
        "AtomicRadius": "175",
        "IonizationEnergy": "12968",
        "ElectronAffinity": "3617",
        "StandardState": "Gas",
        "MeltingPoint": "171.65",
        "BoilingPoint": "239.11",
        "Density": "0.003214",
        "YearDiscovered": "1774"
    },
    {
        "AtomicNumber": "18",
        "Symbol": "Ar",
        "Name_es": "Argón",
        "Name_en": "Argon",
        "OxidationStates": "0",
        "GroupBlock": "Noble gas",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "39.9",
        "CPKHexColor": "80D1E3",
        "ElectronConfiguration": "[Ne]3s2 3p6",
        "Electronegativity": "",
        "AtomicRadius": "188",
        "IonizationEnergy": "15760",
        "ElectronAffinity": "",
        "StandardState": "Gas",
        "MeltingPoint": "83.8",
        "BoilingPoint": "87.3",
        "Density": "0.0017837",
        "YearDiscovered": "1894"
    },
    {
        "AtomicNumber": "19",
        "Symbol": "K",
        "Name_es": "Potasio",
        "Name_en": "Potassium",
        "OxidationStates": "1",
        "GroupBlock": "Alkali metal",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "39.0983",
        "CPKHexColor": "8F40D4",
        "ElectronConfiguration": "[Ar]4s1",
        "Electronegativity": "0.82",
        "AtomicRadius": "275",
        "IonizationEnergy": "4341",
        "ElectronAffinity": "501",
        "StandardState": "Solid",
        "MeltingPoint": "336.53",
        "BoilingPoint": "1032",
        "Density": "0.89",
        "YearDiscovered": "1807"
    },
    {
        "AtomicNumber": "20",
        "Symbol": "Ca",
        "Name_es": "Calcio",
        "Name_en": "Calcium",
        "OxidationStates": "2",
        "GroupBlock": "Alkaline earth metal",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "40.08",
        "CPKHexColor": "3DFF00",
        "ElectronConfiguration": "[Ar]4s2",
        "Electronegativity": "1",
        "AtomicRadius": "231",
        "IonizationEnergy": "6113",
        "ElectronAffinity": "",
        "StandardState": "Solid",
        "MeltingPoint": "1115",
        "BoilingPoint": "1757",
        "Density": "1.54",
        "YearDiscovered": "Ancient"
    },
    {
        "AtomicNumber": "21",
        "Symbol": "Sc",
        "Name_es": "Escandio",
        "Name_en": "Scandium",
        "OxidationStates": "3",
        "GroupBlock": "Transition metal",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "44.95591",
        "CPKHexColor": "E6E6E6",
        "ElectronConfiguration": "[Ar]4s2 3d1",
        "Electronegativity": "1.36",
        "AtomicRadius": "211",
        "IonizationEnergy": "6561",
        "ElectronAffinity": "188",
        "StandardState": "Solid",
        "MeltingPoint": "1814",
        "BoilingPoint": "3109",
        "Density": "2.99",
        "YearDiscovered": "1879"
    },
    {
        "AtomicNumber": "22",
        "Symbol": "Ti",
        "Name_es": "Titanio",
        "Name_en": "Titanium",
        "OxidationStates": "+4, +3, +2",
        "GroupBlock": "Transition metal",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "47867",
        "CPKHexColor": "BFC2C7",
        "ElectronConfiguration": "[Ar]4s2 3d2",
        "Electronegativity": "1.54",
        "AtomicRadius": "187",
        "IonizationEnergy": "6828",
        "ElectronAffinity": "79",
        "StandardState": "Solid",
        "MeltingPoint": "1941",
        "BoilingPoint": "3560",
        "Density": "4.5",
        "YearDiscovered": "1791"
    },
    {
        "AtomicNumber": "23",
        "Symbol": "V",
        "Name_es": "Vanadio",
        "Name_en": "Vanadium",
        "OxidationStates": "+5, +4, +3, +2",
        "GroupBlock": "Transition metal",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "50.9415",
        "CPKHexColor": "A6A6AB",
        "ElectronConfiguration": "[Ar]4s2 3d3",
        "Electronegativity": "1.63",
        "AtomicRadius": "179",
        "IonizationEnergy": "6746",
        "ElectronAffinity": "525",
        "StandardState": "Solid",
        "MeltingPoint": "2183",
        "BoilingPoint": "3680",
        "Density": "6.0",
        "YearDiscovered": "1801"
    },
    {
        "AtomicNumber": "24",
        "Symbol": "Cr",
        "Name_es": "Cromo",
        "Name_en": "Chromium",
        "OxidationStates": "+6, +3, +2",
        "GroupBlock": "Transition metal",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "51996",
        "CPKHexColor": "8A99C7",
        "ElectronConfiguration": "[Ar]3d5 4s1",
        "Electronegativity": "1.66",
        "AtomicRadius": "189",
        "IonizationEnergy": "6767",
        "ElectronAffinity": "666",
        "StandardState": "Solid",
        "MeltingPoint": "2180",
        "BoilingPoint": "2944",
        "Density": "7.15",
        "YearDiscovered": "1797"
    },
    {
        "AtomicNumber": "25",
        "Symbol": "Mn",
        "Name_es": "Manganeso",
        "Name_en": "Manganese",
        "OxidationStates": "+7, +4, +3, +2",
        "GroupBlock": "Transition metal",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "54.93804",
        "CPKHexColor": "9C7AC7",
        "ElectronConfiguration": "[Ar]4s2 3d5",
        "Electronegativity": "1.55",
        "AtomicRadius": "197",
        "IonizationEnergy": "7434",
        "ElectronAffinity": "",
        "StandardState": "Solid",
        "MeltingPoint": "1519",
        "BoilingPoint": "2334",
        "Density": "7.3",
        "YearDiscovered": "1774"
    },
    {
        "AtomicNumber": "26",
        "Symbol": "Fe",
        "Name_es": "Hierro",
        "Name_en": "Iron",
        "OxidationStates": "+3, +2",
        "GroupBlock": "Transition metal",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "55.84",
        "CPKHexColor": "E06633",
        "ElectronConfiguration": "[Ar]4s2 3d6",
        "Electronegativity": "1.83",
        "AtomicRadius": "194",
        "IonizationEnergy": "7902",
        "ElectronAffinity": "163",
        "StandardState": "Solid",
        "MeltingPoint": "1811",
        "BoilingPoint": "3134",
        "Density": "7874",
        "YearDiscovered": "Ancient"
    },
    {
        "AtomicNumber": "27",
        "Symbol": "Co",
        "Name_es": "Cobalto",
        "Name_en": "Cobalt",
        "OxidationStates": "+3, +2",
        "GroupBlock": "Transition metal",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "58.93319",
        "CPKHexColor": "F090A0",
        "ElectronConfiguration": "[Ar]4s2 3d7",
        "Electronegativity": "1.88",
        "AtomicRadius": "192",
        "IonizationEnergy": "7881",
        "ElectronAffinity": "661",
        "StandardState": "Solid",
        "MeltingPoint": "1768",
        "BoilingPoint": "3200",
        "Density": "8.86",
        "YearDiscovered": "1735"
    },
    {
        "AtomicNumber": "28",
        "Symbol": "Ni",
        "Name_es": "Níquel",
        "Name_en": "Nickel",
        "OxidationStates": "+3, +2",
        "GroupBlock": "Transition metal",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "58693",
        "CPKHexColor": "50D050",
        "ElectronConfiguration": "[Ar]4s2 3d8",
        "Electronegativity": "1.91",
        "AtomicRadius": "163",
        "IonizationEnergy": "7640",
        "ElectronAffinity": "1156",
        "StandardState": "Solid",
        "MeltingPoint": "1728",
        "BoilingPoint": "3186",
        "Density": "8912",
        "YearDiscovered": "1751"
    },
    {
        "AtomicNumber": "29",
        "Symbol": "Cu",
        "Name_es": "Cobre",
        "Name_en": "Copper",
        "OxidationStates": "+2, +1",
        "GroupBlock": "Transition metal",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "63.55",
        "CPKHexColor": "C88033",
        "ElectronConfiguration": "[Ar]4s1 3d10",
        "Electronegativity": "1.9",
        "AtomicRadius": "140",
        "IonizationEnergy": "7726",
        "ElectronAffinity": "1228",
        "StandardState": "Solid",
        "MeltingPoint": "1357.77",
        "BoilingPoint": "2835",
        "Density": "8933",
        "YearDiscovered": "Ancient"
    },
    {
        "AtomicNumber": "30",
        "Symbol": "Zn",
        "Name_es": "Zinc",
        "Name_en": "Zinc",
        "OxidationStates": "2",
        "GroupBlock": "Transition metal",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "65.4",
        "CPKHexColor": "7D80B0",
        "ElectronConfiguration": "[Ar]4s2 3d10",
        "Electronegativity": "1.65",
        "AtomicRadius": "139",
        "IonizationEnergy": "9394",
        "ElectronAffinity": "",
        "StandardState": "Solid",
        "MeltingPoint": "692.68",
        "BoilingPoint": "1180",
        "Density": "7134",
        "YearDiscovered": "1746"
    },
    {
        "AtomicNumber": "31",
        "Symbol": "Ga",
        "Name_es": "Galio",
        "Name_en": "Gallium",
        "OxidationStates": "3",
        "GroupBlock": "Post-transition metal",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "69723",
        "CPKHexColor": "C28F8F",
        "ElectronConfiguration": "[Ar]4s2 3d10 4p1",
        "Electronegativity": "1.81",
        "AtomicRadius": "187",
        "IonizationEnergy": "5999",
        "ElectronAffinity": "0.3",
        "StandardState": "Solid",
        "MeltingPoint": "302.91",
        "BoilingPoint": "2477",
        "Density": "5.91",
        "YearDiscovered": "1875"
    },
    {
        "AtomicNumber": "32",
        "Symbol": "Ge",
        "Name_es": "Germanio",
        "Name_en": "Germanium",
        "OxidationStates": "+4, +2",
        "GroupBlock": "Metalloid",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "72.63",
        "CPKHexColor": "668F8F",
        "ElectronConfiguration": "[Ar]4s2 3d10 4p2",
        "Electronegativity": "2.01",
        "AtomicRadius": "211",
        "IonizationEnergy": "7900",
        "ElectronAffinity": "1.35",
        "StandardState": "Solid",
        "MeltingPoint": "1211.4",
        "BoilingPoint": "3106",
        "Density": "5323",
        "YearDiscovered": "1886"
    },
    {
        "AtomicNumber": "33",
        "Symbol": "As",
        "Name_es": "Arsénico",
        "Name_en": "Arsenic",
        "OxidationStates": "+5, +3, -3",
        "GroupBlock": "Metalloid",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "74.92159",
        "CPKHexColor": "BD80E3",
        "ElectronConfiguration": "[Ar]4s2 3d10 4p3",
        "Electronegativity": "2.18",
        "AtomicRadius": "185",
        "IonizationEnergy": "9815",
        "ElectronAffinity": "0.81",
        "StandardState": "Solid",
        "MeltingPoint": "1090",
        "BoilingPoint": "887",
        "Density": "5776",
        "YearDiscovered": "Ancient"
    },
    {
        "AtomicNumber": "34",
        "Symbol": "Se",
        "Name_es": "Selenio",
        "Name_en": "Selenium",
        "OxidationStates": "+6, +4, -2",
        "GroupBlock": "Nonmetal",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "78.97",
        "CPKHexColor": "FFA100",
        "ElectronConfiguration": "[Ar]4s2 3d10 4p4",
        "Electronegativity": "2.55",
        "AtomicRadius": "190",
        "IonizationEnergy": "9752",
        "ElectronAffinity": "2021",
        "StandardState": "Solid",
        "MeltingPoint": "493.65",
        "BoilingPoint": "958",
        "Density": "4809",
        "YearDiscovered": "1817"
    },
    {
        "AtomicNumber": "35",
        "Symbol": "Br",
        "Name_es": "Bromo",
        "Name_en": "Bromine",
        "OxidationStates": "+5, +1, -1",
        "GroupBlock": "Halogen",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "79.90",
        "CPKHexColor": "A62929",
        "ElectronConfiguration": "[Ar]4s2 3d10 4p5",
        "Electronegativity": "2.96",
        "AtomicRadius": "183",
        "IonizationEnergy": "11814",
        "ElectronAffinity": "3365",
        "StandardState": "Liquid",
        "MeltingPoint": "265.95",
        "BoilingPoint": "331.95",
        "Density": "3.11",
        "YearDiscovered": "1826"
    },
    {
        "AtomicNumber": "36",
        "Symbol": "Kr",
        "Name_es": "Kriptón",
        "Name_en": "Krypton",
        "OxidationStates": "0",
        "GroupBlock": "Noble gas",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "83.80",
        "CPKHexColor": "5CB8D1",
        "ElectronConfiguration": "[Ar]4s2 3d10 4p6",
        "Electronegativity": "3",
        "AtomicRadius": "202",
        "IonizationEnergy": "14000",
        "ElectronAffinity": "",
        "StandardState": "Gas",
        "MeltingPoint": "115.79",
        "BoilingPoint": "119.93",
        "Density": "0.003733",
        "YearDiscovered": "1898"
    },
    {
        "AtomicNumber": "37",
        "Symbol": "Rb",
        "Name_es": "Rubidio",
        "Name_en": "Rubidium",
        "OxidationStates": "1",
        "GroupBlock": "Alkali metal",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "85468",
        "CPKHexColor": "702EB0",
        "ElectronConfiguration": "[Kr]5s1",
        "Electronegativity": "0.82",
        "AtomicRadius": "303",
        "IonizationEnergy": "4177",
        "ElectronAffinity": "468",
        "StandardState": "Solid",
        "MeltingPoint": "312.46",
        "BoilingPoint": "961",
        "Density": "1.53",
        "YearDiscovered": "1861"
    },
    {
        "AtomicNumber": "38",
        "Symbol": "Sr",
        "Name_es": "Estroncio",
        "Name_en": "Strontium",
        "OxidationStates": "2",
        "GroupBlock": "Alkaline earth metal",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "87.62",
        "CPKHexColor": "00FF00",
        "ElectronConfiguration": "[Kr]5s2",
        "Electronegativity": "0.95",
        "AtomicRadius": "249",
        "IonizationEnergy": "5695",
        "ElectronAffinity": "",
        "StandardState": "Solid",
        "MeltingPoint": "1050",
        "BoilingPoint": "1655",
        "Density": "2.64",
        "YearDiscovered": "1790"
    },
    {
        "AtomicNumber": "39",
        "Symbol": "Y",
        "Name_es": "Ytrio",
        "Name_en": "Yttrium",
        "OxidationStates": "3",
        "GroupBlock": "Transition metal",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "88.90584",
        "CPKHexColor": "94FFFF",
        "ElectronConfiguration": "[Kr]5s2 4d1",
        "Electronegativity": "1.22",
        "AtomicRadius": "219",
        "IonizationEnergy": "6217",
        "ElectronAffinity": "307",
        "StandardState": "Solid",
        "MeltingPoint": "1795",
        "BoilingPoint": "3618",
        "Density": "4.47",
        "YearDiscovered": "1794"
    },
    {
        "AtomicNumber": "40",
        "Symbol": "Zr",
        "Name_es": "Zirconio",
        "Name_en": "Zirconium",
        "OxidationStates": "4",
        "GroupBlock": "Transition metal",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "91.22",
        "CPKHexColor": "94E0E0",
        "ElectronConfiguration": "[Kr]5s2 4d2",
        "Electronegativity": "1.33",
        "AtomicRadius": "186",
        "IonizationEnergy": "6634",
        "ElectronAffinity": "426",
        "StandardState": "Solid",
        "MeltingPoint": "2128",
        "BoilingPoint": "4682",
        "Density": "6.52",
        "YearDiscovered": "1789"
    },
    {
        "AtomicNumber": "41",
        "Symbol": "Nb",
        "Name_es": "Niobio",
        "Name_en": "Niobium",
        "OxidationStates": "+5, +3",
        "GroupBlock": "Transition metal",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "92.90637",
        "CPKHexColor": "73C2C9",
        "ElectronConfiguration": "[Kr]5s1 4d4",
        "Electronegativity": "1.6",
        "AtomicRadius": "207",
        "IonizationEnergy": "6759",
        "ElectronAffinity": "893",
        "StandardState": "Solid",
        "MeltingPoint": "2750",
        "BoilingPoint": "5017",
        "Density": "8.57",
        "YearDiscovered": "1801"
    },
    {
        "AtomicNumber": "42",
        "Symbol": "Mo",
        "Name_es": "Molibdeno",
        "Name_en": "Molybdenum",
        "OxidationStates": "6",
        "GroupBlock": "Transition metal",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "95.95",
        "CPKHexColor": "54B5B5",
        "ElectronConfiguration": "[Kr]5s1 4d5",
        "Electronegativity": "2.16",
        "AtomicRadius": "209",
        "IonizationEnergy": "7092",
        "ElectronAffinity": "746",
        "StandardState": "Solid",
        "MeltingPoint": "2896",
        "BoilingPoint": "4912",
        "Density": "10.2",
        "YearDiscovered": "1778"
    },
    {
        "AtomicNumber": "43",
        "Symbol": "Tc",
        "Name_es": "Tecnecio",
        "Name_en": "Technetium",
        "OxidationStates": "+7, +6, +4",
        "GroupBlock": "Transition metal",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "96.90636",
        "CPKHexColor": "3B9E9E",
        "ElectronConfiguration": "[Kr]5s2 4d5",
        "Electronegativity": "1.9",
        "AtomicRadius": "209",
        "IonizationEnergy": "7.28",
        "ElectronAffinity": "0.55",
        "StandardState": "Solid",
        "MeltingPoint": "2430",
        "BoilingPoint": "4538",
        "Density": "11",
        "YearDiscovered": "1937"
    },
    {
        "AtomicNumber": "44",
        "Symbol": "Ru",
        "Name_es": "Rutenio",
        "Name_en": "Ruthenium",
        "OxidationStates": "3",
        "GroupBlock": "Transition metal",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "101.1",
        "CPKHexColor": "248F8F",
        "ElectronConfiguration": "[Kr]5s1 4d7",
        "Electronegativity": "2.2",
        "AtomicRadius": "207",
        "IonizationEnergy": "7361",
        "ElectronAffinity": "1.05",
        "StandardState": "Solid",
        "MeltingPoint": "2607",
        "BoilingPoint": "4423",
        "Density": "12.1",
        "YearDiscovered": "1827"
    },
    {
        "AtomicNumber": "45",
        "Symbol": "Rh",
        "Name_es": "Rodio",
        "Name_en": "Rhodium",
        "OxidationStates": "3",
        "GroupBlock": "Transition metal",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "102.9055",
        "CPKHexColor": "0A7D8C",
        "ElectronConfiguration": "[Kr]5s1 4d8",
        "Electronegativity": "2.28",
        "AtomicRadius": "195",
        "IonizationEnergy": "7459",
        "ElectronAffinity": "1137",
        "StandardState": "Solid",
        "MeltingPoint": "2237",
        "BoilingPoint": "3968",
        "Density": "12.4",
        "YearDiscovered": "1803"
    },
    {
        "AtomicNumber": "46",
        "Symbol": "Pd",
        "Name_es": "Paladio",
        "Name_en": "Palladium",
        "OxidationStates": "+3, +2",
        "GroupBlock": "Transition metal",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "106.42",
        "CPKHexColor": "6985",
        "ElectronConfiguration": "[Kr]4d10",
        "Electronegativity": "2.2",
        "AtomicRadius": "202",
        "IonizationEnergy": "8337",
        "ElectronAffinity": "557",
        "StandardState": "Solid",
        "MeltingPoint": "1828.05",
        "BoilingPoint": "3236",
        "Density": "12.0",
        "YearDiscovered": "1803"
    },
    {
        "AtomicNumber": "47",
        "Symbol": "Ag",
        "Name_es": "Plata",
        "Name_en": "Silver",
        "OxidationStates": "1",
        "GroupBlock": "Transition metal",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "107868",
        "CPKHexColor": "C0C0C0",
        "ElectronConfiguration": "[Kr]5s1 4d10",
        "Electronegativity": "1.93",
        "AtomicRadius": "172",
        "IonizationEnergy": "7576",
        "ElectronAffinity": "1302",
        "StandardState": "Solid",
        "MeltingPoint": "1234.93",
        "BoilingPoint": "2435",
        "Density": "10501",
        "YearDiscovered": "Ancient"
    },
    {
        "AtomicNumber": "48",
        "Symbol": "Cd",
        "Name_es": "Cadmio",
        "Name_en": "Cadmium",
        "OxidationStates": "2",
        "GroupBlock": "Transition metal",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "112.41",
        "CPKHexColor": "FFD98F",
        "ElectronConfiguration": "[Kr]5s2 4d10",
        "Electronegativity": "1.69",
        "AtomicRadius": "158",
        "IonizationEnergy": "8994",
        "ElectronAffinity": "",
        "StandardState": "Solid",
        "MeltingPoint": "594.22",
        "BoilingPoint": "1040",
        "Density": "8.69",
        "YearDiscovered": "1817"
    },
    {
        "AtomicNumber": "49",
        "Symbol": "In",
        "Name_es": "Indio",
        "Name_en": "Indium",
        "OxidationStates": "3",
        "GroupBlock": "Post-transition metal",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "114818",
        "CPKHexColor": "A67573",
        "ElectronConfiguration": "[Kr]5s2 4d10 5p1",
        "Electronegativity": "1.78",
        "AtomicRadius": "193",
        "IonizationEnergy": "5786",
        "ElectronAffinity": "0.3",
        "StandardState": "Solid",
        "MeltingPoint": "429.75",
        "BoilingPoint": "2345",
        "Density": "7.31",
        "YearDiscovered": "1863"
    },
    {
        "AtomicNumber": "50",
        "Symbol": "Sn",
        "Name_es": "Estaño",
        "Name_en": "Tin",
        "OxidationStates": "+4, +2",
        "GroupBlock": "Post-transition metal",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "118.71",
        "CPKHexColor": "668080",
        "ElectronConfiguration": "[Kr]5s2 4d10 5p2",
        "Electronegativity": "1.96",
        "AtomicRadius": "217",
        "IonizationEnergy": "7344",
        "ElectronAffinity": "1.2",
        "StandardState": "Solid",
        "MeltingPoint": "505.08",
        "BoilingPoint": "2875",
        "Density": "7287",
        "YearDiscovered": "Ancient"
    },
    {
        "AtomicNumber": "51",
        "Symbol": "Sb",
        "Name_es": "Antimonio",
        "Name_en": "Antimony",
        "OxidationStates": "+5, +3, -3",
        "GroupBlock": "Metalloid",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "121760",
        "CPKHexColor": "9E63B5",
        "ElectronConfiguration": "[Kr]5s2 4d10 5p3",
        "Electronegativity": "2.05",
        "AtomicRadius": "206",
        "IonizationEnergy": "8.64",
        "ElectronAffinity": "1.07",
        "StandardState": "Solid",
        "MeltingPoint": "903.78",
        "BoilingPoint": "1860",
        "Density": "6685",
        "YearDiscovered": "Ancient"
    },
    {
        "AtomicNumber": "52",
        "Symbol": "Te",
        "Name_es": "Teluro",
        "Name_en": "Tellurium",
        "OxidationStates": "+6, +4, -2",
        "GroupBlock": "Metalloid",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "127.6",
        "CPKHexColor": "D47A00",
        "ElectronConfiguration": "[Kr]5s2 4d10 5p4",
        "Electronegativity": "2.1",
        "AtomicRadius": "206",
        "IonizationEnergy": "9010",
        "ElectronAffinity": "1971",
        "StandardState": "Solid",
        "MeltingPoint": "722.66",
        "BoilingPoint": "1261",
        "Density": "6232",
        "YearDiscovered": "1782"
    },
    {
        "AtomicNumber": "53",
        "Symbol": "I",
        "Name_es": "Yodo",
        "Name_en": "Iodine",
        "OxidationStates": "+7, +5, +1, -1",
        "GroupBlock": "Halogen",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "126.9045",
        "CPKHexColor": "940094",
        "ElectronConfiguration": "[Kr]5s2 4d10 5p5",
        "Electronegativity": "2.66",
        "AtomicRadius": "198",
        "IonizationEnergy": "10451",
        "ElectronAffinity": "3059",
        "StandardState": "Solid",
        "MeltingPoint": "386.85",
        "BoilingPoint": "457.55",
        "Density": "4.93",
        "YearDiscovered": "1811"
    },
    {
        "AtomicNumber": "54",
        "Symbol": "Xe",
        "Name_es": "Xenón",
        "Name_en": "Xenon",
        "OxidationStates": "0",
        "GroupBlock": "Noble gas",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "131.29",
        "CPKHexColor": "429EB0",
        "ElectronConfiguration": "[Kr]5s2 4d10 5p6",
        "Electronegativity": "2.6",
        "AtomicRadius": "216",
        "IonizationEnergy": "12130",
        "ElectronAffinity": "",
        "StandardState": "Gas",
        "MeltingPoint": "161.36",
        "BoilingPoint": "165.03",
        "Density": "0.005887",
        "YearDiscovered": "1898"
    },
    {
        "AtomicNumber": "55",
        "Symbol": "Cs",
        "Name_es": "Cesio",
        "Name_en": "Cesium",
        "OxidationStates": "1",
        "GroupBlock": "Alkali metal",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "132.9054520",
        "CPKHexColor": "57178F",
        "ElectronConfiguration": "[Xe]6s1",
        "Electronegativity": "0.79",
        "AtomicRadius": "343",
        "IonizationEnergy": "3894",
        "ElectronAffinity": "472",
        "StandardState": "Solid",
        "MeltingPoint": "301.59",
        "BoilingPoint": "944",
        "Density": "1.93",
        "YearDiscovered": "1860"
    },
    {
        "AtomicNumber": "56",
        "Symbol": "Ba",
        "Name_es": "Bario",
        "Name_en": "Barium",
        "OxidationStates": "2",
        "GroupBlock": "Alkaline earth metal",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "137.33",
        "CPKHexColor": "00C900",
        "ElectronConfiguration": "[Xe]6s2",
        "Electronegativity": "0.89",
        "AtomicRadius": "268",
        "IonizationEnergy": "5212",
        "ElectronAffinity": "",
        "StandardState": "Solid",
        "MeltingPoint": "1000",
        "BoilingPoint": "2170",
        "Density": "3.62",
        "YearDiscovered": "1808"
    },
    {
        "AtomicNumber": "57",
        "Symbol": "La",
        "Name_es": "Lantano",
        "Name_en": "Lanthanum",
        "OxidationStates": "3",
        "GroupBlock": "Lanthanide",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "138.9055",
        "CPKHexColor": "70D4FF",
        "ElectronConfiguration": "[Xe]6s2 5d1",
        "Electronegativity": "1.1",
        "AtomicRadius": "240",
        "IonizationEnergy": "5577",
        "ElectronAffinity": "0.5",
        "StandardState": "Solid",
        "MeltingPoint": "1191",
        "BoilingPoint": "3737",
        "Density": "6.15",
        "YearDiscovered": "1839"
    },
    {
        "AtomicNumber": "58",
        "Symbol": "Ce",
        "Name_es": "Cerio",
        "Name_en": "Cerium",
        "OxidationStates": "+4, +3",
        "GroupBlock": "Lanthanide",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "140116",
        "CPKHexColor": "FFFFC7",
        "ElectronConfiguration": "[Xe]6s2 4f1 5d1",
        "Electronegativity": "1.12",
        "AtomicRadius": "235",
        "IonizationEnergy": "5539",
        "ElectronAffinity": "0.5",
        "StandardState": "Solid",
        "MeltingPoint": "1071",
        "BoilingPoint": "3697",
        "Density": "6770",
        "YearDiscovered": "1803"
    },
    {
        "AtomicNumber": "59",
        "Symbol": "Pr",
        "Name_es": "Praseodimio",
        "Name_en": "Praseodymium",
        "OxidationStates": "3",
        "GroupBlock": "Lanthanide",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "140.90766",
        "CPKHexColor": "D9FFC7",
        "ElectronConfiguration": "[Xe]6s2 4f3",
        "Electronegativity": "1.13",
        "AtomicRadius": "239",
        "IonizationEnergy": "5464",
        "ElectronAffinity": "",
        "StandardState": "Solid",
        "MeltingPoint": "1204",
        "BoilingPoint": "3793",
        "Density": "6.77",
        "YearDiscovered": "1885"
    },
    {
        "AtomicNumber": "60",
        "Symbol": "Nd",
        "Name_es": "Neodimio",
        "Name_en": "Neodymium",
        "OxidationStates": "3",
        "GroupBlock": "Lanthanide",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "144.24",
        "CPKHexColor": "C7FFC7",
        "ElectronConfiguration": "[Xe]6s2 4f4",
        "Electronegativity": "1.14",
        "AtomicRadius": "229",
        "IonizationEnergy": "5525",
        "ElectronAffinity": "",
        "StandardState": "Solid",
        "MeltingPoint": "1294",
        "BoilingPoint": "3347",
        "Density": "7.01",
        "YearDiscovered": "1885"
    },
    {
        "AtomicNumber": "61",
        "Symbol": "Pm",
        "Name_es": "Prometio",
        "Name_en": "Promethium",
        "OxidationStates": "3",
        "GroupBlock": "Lanthanide",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "144.91276",
        "CPKHexColor": "A3FFC7",
        "ElectronConfiguration": "[Xe]6s2 4f5",
        "Electronegativity": "",
        "AtomicRadius": "236",
        "IonizationEnergy": "5.55",
        "ElectronAffinity": "",
        "StandardState": "Solid",
        "MeltingPoint": "1315",
        "BoilingPoint": "3273",
        "Density": "7.26",
        "YearDiscovered": "1945"
    },
    {
        "AtomicNumber": "62",
        "Symbol": "Sm",
        "Name_es": "Samario",
        "Name_en": "Samarium",
        "OxidationStates": "+3, +2",
        "GroupBlock": "Lanthanide",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "150.4",
        "CPKHexColor": "8FFFC7",
        "ElectronConfiguration": "[Xe]6s2 4f6",
        "Electronegativity": "1.17",
        "AtomicRadius": "229",
        "IonizationEnergy": "5644",
        "ElectronAffinity": "",
        "StandardState": "Solid",
        "MeltingPoint": "1347",
        "BoilingPoint": "2067",
        "Density": "7.52",
        "YearDiscovered": "1879"
    },
    {
        "AtomicNumber": "63",
        "Symbol": "Eu",
        "Name_es": "Europio",
        "Name_en": "Europium",
        "OxidationStates": "+3, +2",
        "GroupBlock": "Lanthanide",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "151964",
        "CPKHexColor": "61FFC7",
        "ElectronConfiguration": "[Xe]6s2 4f7",
        "Electronegativity": "",
        "AtomicRadius": "233",
        "IonizationEnergy": "5670",
        "ElectronAffinity": "",
        "StandardState": "Solid",
        "MeltingPoint": "1095",
        "BoilingPoint": "1802",
        "Density": "5.24",
        "YearDiscovered": "1901"
    },
    {
        "AtomicNumber": "64",
        "Symbol": "Gd",
        "Name_es": "Gadolinio",
        "Name_en": "Gadolinium",
        "OxidationStates": "3",
        "GroupBlock": "Lanthanide",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "157.25",
        "CPKHexColor": "45FFC7",
        "ElectronConfiguration": "[Xe]6s2 4f7 5d1",
        "Electronegativity": "1.2",
        "AtomicRadius": "237",
        "IonizationEnergy": "6150",
        "ElectronAffinity": "",
        "StandardState": "Solid",
        "MeltingPoint": "1586",
        "BoilingPoint": "3546",
        "Density": "7.90",
        "YearDiscovered": "1880"
    },
    {
        "AtomicNumber": "65",
        "Symbol": "Tb",
        "Name_es": "Terbio",
        "Name_en": "Terbium",
        "OxidationStates": "3",
        "GroupBlock": "Lanthanide",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "158.92535",
        "CPKHexColor": "30FFC7",
        "ElectronConfiguration": "[Xe]6s2 4f9",
        "Electronegativity": "",
        "AtomicRadius": "221",
        "IonizationEnergy": "5864",
        "ElectronAffinity": "",
        "StandardState": "Solid",
        "MeltingPoint": "1629",
        "BoilingPoint": "3503",
        "Density": "8.23",
        "YearDiscovered": "1843"
    },
    {
        "AtomicNumber": "66",
        "Symbol": "Dy",
        "Name_es": "Disprosio",
        "Name_en": "Dysprosium",
        "OxidationStates": "3",
        "GroupBlock": "Lanthanide",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "162500",
        "CPKHexColor": "1FFFC7",
        "ElectronConfiguration": "[Xe]6s2 4f10",
        "Electronegativity": "1.22",
        "AtomicRadius": "229",
        "IonizationEnergy": "5939",
        "ElectronAffinity": "",
        "StandardState": "Solid",
        "MeltingPoint": "1685",
        "BoilingPoint": "2840",
        "Density": "8.55",
        "YearDiscovered": "1886"
    },
    {
        "AtomicNumber": "67",
        "Symbol": "Ho",
        "Name_es": "Holmio",
        "Name_en": "Holmium",
        "OxidationStates": "3",
        "GroupBlock": "Lanthanide",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "164.93033",
        "CPKHexColor": "00FF9C",
        "ElectronConfiguration": "[Xe]6s2 4f11",
        "Electronegativity": "1.23",
        "AtomicRadius": "216",
        "IonizationEnergy": "6022",
        "ElectronAffinity": "",
        "StandardState": "Solid",
        "MeltingPoint": "1747",
        "BoilingPoint": "2973",
        "Density": "8.80",
        "YearDiscovered": "1878"
    },
    {
        "AtomicNumber": "68",
        "Symbol": "Er",
        "Name_es": "Erbio",
        "Name_en": "Erbium",
        "OxidationStates": "3",
        "GroupBlock": "Lanthanide",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "167.26",
        "CPKHexColor": "",
        "ElectronConfiguration": "[Xe]6s2 4f12",
        "Electronegativity": "1.24",
        "AtomicRadius": "235",
        "IonizationEnergy": "6108",
        "ElectronAffinity": "",
        "StandardState": "Solid",
        "MeltingPoint": "1802",
        "BoilingPoint": "3141",
        "Density": "9.07",
        "YearDiscovered": "1843"
    },
    {
        "AtomicNumber": "69",
        "Symbol": "Tm",
        "Name_es": "Tulio",
        "Name_en": "Thulium",
        "OxidationStates": "3",
        "GroupBlock": "Lanthanide",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "168.93422",
        "CPKHexColor": "00D452",
        "ElectronConfiguration": "[Xe]6s2 4f13",
        "Electronegativity": "1.25",
        "AtomicRadius": "227",
        "IonizationEnergy": "6184",
        "ElectronAffinity": "",
        "StandardState": "Solid",
        "MeltingPoint": "1818",
        "BoilingPoint": "2223",
        "Density": "9.32",
        "YearDiscovered": "1879"
    },
    {
        "AtomicNumber": "70",
        "Symbol": "Yb",
        "Name_es": "Yterbio",
        "Name_en": "Ytterbium",
        "OxidationStates": "+3, +2",
        "GroupBlock": "Lanthanide",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "173.05",
        "CPKHexColor": "00BF38",
        "ElectronConfiguration": "[Xe]6s2 4f14",
        "Electronegativity": "",
        "AtomicRadius": "242",
        "IonizationEnergy": "6254",
        "ElectronAffinity": "",
        "StandardState": "Solid",
        "MeltingPoint": "1092",
        "BoilingPoint": "1469",
        "Density": "6.90",
        "YearDiscovered": "1878"
    },
    {
        "AtomicNumber": "71",
        "Symbol": "Lu",
        "Name_es": "Lutecio",
        "Name_en": "Lutetium",
        "OxidationStates": "3",
        "GroupBlock": "Lanthanide",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "174.9667",
        "CPKHexColor": "00AB24",
        "ElectronConfiguration": "[Xe]6s2 4f14 5d1",
        "Electronegativity": "1.27",
        "AtomicRadius": "221",
        "IonizationEnergy": "5426",
        "ElectronAffinity": "",
        "StandardState": "Solid",
        "MeltingPoint": "1936",
        "BoilingPoint": "3675",
        "Density": "9.84",
        "YearDiscovered": "1907"
    },
    {
        "AtomicNumber": "72",
        "Symbol": "Hf",
        "Name_es": "Hafnio",
        "Name_en": "Hafnium",
        "OxidationStates": "4",
        "GroupBlock": "Transition metal",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "178.49",
        "CPKHexColor": "4DC2FF",
        "ElectronConfiguration": "[Xe]6s2 4f14 5d2",
        "Electronegativity": "1.3",
        "AtomicRadius": "212",
        "IonizationEnergy": "6825",
        "ElectronAffinity": "",
        "StandardState": "Solid",
        "MeltingPoint": "2506",
        "BoilingPoint": "4876",
        "Density": "13.3",
        "YearDiscovered": "1923"
    },
    {
        "AtomicNumber": "73",
        "Symbol": "Ta",
        "Name_es": "Tantalio",
        "Name_en": "Tantalum",
        "OxidationStates": "5",
        "GroupBlock": "Transition metal",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "180.9479",
        "CPKHexColor": "4DA6FF",
        "ElectronConfiguration": "[Xe]6s2 4f14 5d3",
        "Electronegativity": "1.5",
        "AtomicRadius": "217",
        "IonizationEnergy": "7.89",
        "ElectronAffinity": "322",
        "StandardState": "Solid",
        "MeltingPoint": "3290",
        "BoilingPoint": "5731",
        "Density": "16.4",
        "YearDiscovered": "1802"
    },
    {
        "AtomicNumber": "74",
        "Symbol": "W",
        "Name_es": "Wolframio",
        "Name_en": "Tungsten",
        "OxidationStates": "6",
        "GroupBlock": "Transition metal",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "183.84",
        "CPKHexColor": "2194D6",
        "ElectronConfiguration": "[Xe]6s2 4f14 5d4",
        "Electronegativity": "2.36",
        "AtomicRadius": "210",
        "IonizationEnergy": "7.98",
        "ElectronAffinity": "815",
        "StandardState": "Solid",
        "MeltingPoint": "3695",
        "BoilingPoint": "5828",
        "Density": "19.3",
        "YearDiscovered": "1783"
    },
    {
        "AtomicNumber": "75",
        "Symbol": "Re",
        "Name_es": "Renio",
        "Name_en": "Rhenium",
        "OxidationStates": "+7, +6, +4",
        "GroupBlock": "Transition metal",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "186207",
        "CPKHexColor": "267DAB",
        "ElectronConfiguration": "[Xe]6s2 4f14 5d5",
        "Electronegativity": "1.9",
        "AtomicRadius": "217",
        "IonizationEnergy": "7.88",
        "ElectronAffinity": "0.15",
        "StandardState": "Solid",
        "MeltingPoint": "3459",
        "BoilingPoint": "5869",
        "Density": "20.8",
        "YearDiscovered": "1925"
    },
    {
        "AtomicNumber": "76",
        "Symbol": "Os",
        "Name_es": "Osmio",
        "Name_en": "Osmium",
        "OxidationStates": "+4, +3",
        "GroupBlock": "Transition metal",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "190.2",
        "CPKHexColor": "266696",
        "ElectronConfiguration": "[Xe]6s2 4f14 5d6",
        "Electronegativity": "2.2",
        "AtomicRadius": "216",
        "IonizationEnergy": "8.7",
        "ElectronAffinity": "1.1",
        "StandardState": "Solid",
        "MeltingPoint": "3306",
        "BoilingPoint": "5285",
        "Density": "22.57",
        "YearDiscovered": "1803"
    },
    {
        "AtomicNumber": "77",
        "Symbol": "Ir",
        "Name_es": "Iridio",
        "Name_en": "Iridium",
        "OxidationStates": "+4, +3",
        "GroupBlock": "Transition metal",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "192.22",
        "CPKHexColor": "175487",
        "ElectronConfiguration": "[Xe]6s2 4f14 5d7",
        "Electronegativity": "2.2",
        "AtomicRadius": "202",
        "IonizationEnergy": "9.1",
        "ElectronAffinity": "1565",
        "StandardState": "Solid",
        "MeltingPoint": "2719",
        "BoilingPoint": "4701",
        "Density": "22.42",
        "YearDiscovered": "1803"
    },
    {
        "AtomicNumber": "78",
        "Symbol": "Pt",
        "Name_es": "Platino",
        "Name_en": "Platinum",
        "OxidationStates": "+4, +2",
        "GroupBlock": "Transition metal",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "195.08",
        "CPKHexColor": "D0D0E0",
        "ElectronConfiguration": "[Xe]6s1 4f14 5d9",
        "Electronegativity": "2.28",
        "AtomicRadius": "209",
        "IonizationEnergy": "9",
        "ElectronAffinity": "2128",
        "StandardState": "Solid",
        "MeltingPoint": "2041.55",
        "BoilingPoint": "4098",
        "Density": "21.46",
        "YearDiscovered": "1735"
    },
    {
        "AtomicNumber": "79",
        "Symbol": "Au",
        "Name_es": "Oro",
        "Name_en": "Gold",
        "OxidationStates": "+3, +1",
        "GroupBlock": "Transition metal",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "196.96657",
        "CPKHexColor": "FFD123",
        "ElectronConfiguration": "[Xe]6s1 4f14 5d10",
        "Electronegativity": "2.54",
        "AtomicRadius": "166",
        "IonizationEnergy": "9226",
        "ElectronAffinity": "2309",
        "StandardState": "Solid",
        "MeltingPoint": "1337.33",
        "BoilingPoint": "3129",
        "Density": "19282",
        "YearDiscovered": "Ancient"
    },
    {
        "AtomicNumber": "80",
        "Symbol": "Hg",
        "Name_es": "Mercurio",
        "Name_en": "Mercury",
        "OxidationStates": "+2, +1",
        "GroupBlock": "Transition metal",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "200.59",
        "CPKHexColor": "B8B8D0",
        "ElectronConfiguration": "[Xe]6s2 4f14 5d10",
        "Electronegativity": "2",
        "AtomicRadius": "209",
        "IonizationEnergy": "10438",
        "ElectronAffinity": "",
        "StandardState": "Liquid",
        "MeltingPoint": "234.32",
        "BoilingPoint": "629.88",
        "Density": "13.5336",
        "YearDiscovered": "Ancient"
    },
    {
        "AtomicNumber": "81",
        "Symbol": "Tl",
        "Name_es": "Talio",
        "Name_en": "Thallium",
        "OxidationStates": "+3, +1",
        "GroupBlock": "Post-transition metal",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "204383",
        "CPKHexColor": "A6544D",
        "ElectronConfiguration": "[Xe]6s2 4f14 5d10 6p1",
        "Electronegativity": "1.62",
        "AtomicRadius": "196",
        "IonizationEnergy": "6108",
        "ElectronAffinity": "0.2",
        "StandardState": "Solid",
        "MeltingPoint": "577",
        "BoilingPoint": "1746",
        "Density": "11.8",
        "YearDiscovered": "1861"
    },
    {
        "AtomicNumber": "82",
        "Symbol": "Pb",
        "Name_es": "Plomo",
        "Name_en": "Lead",
        "OxidationStates": "+4, +2",
        "GroupBlock": "Post-transition metal",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "207",
        "CPKHexColor": "575961",
        "ElectronConfiguration": "[Xe]6s2 4f14 5d10 6p2",
        "Electronegativity": "2.33",
        "AtomicRadius": "202",
        "IonizationEnergy": "7417",
        "ElectronAffinity": "0.36",
        "StandardState": "Solid",
        "MeltingPoint": "600.61",
        "BoilingPoint": "2022",
        "Density": "11342",
        "YearDiscovered": "Ancient"
    },
    {
        "AtomicNumber": "83",
        "Symbol": "Bi",
        "Name_es": "Bismuto",
        "Name_en": "Bismuth",
        "OxidationStates": "+5, +3",
        "GroupBlock": "Post-transition metal",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "208.98040",
        "CPKHexColor": "9E4FB5",
        "ElectronConfiguration": "[Xe]6s2 4f14 5d10 6p3",
        "Electronegativity": "2.02",
        "AtomicRadius": "207",
        "IonizationEnergy": "7289",
        "ElectronAffinity": "946",
        "StandardState": "Solid",
        "MeltingPoint": "544.55",
        "BoilingPoint": "1837",
        "Density": "9807",
        "YearDiscovered": "1753"
    },
    {
        "AtomicNumber": "84",
        "Symbol": "Po",
        "Name_es": "Polonio",
        "Name_en": "Polonium",
        "OxidationStates": "+4, +2",
        "GroupBlock": "Metalloid",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "208.98243",
        "CPKHexColor": "AB5C00",
        "ElectronConfiguration": "[Xe]6s2 4f14 5d10 6p4",
        "Electronegativity": "2",
        "AtomicRadius": "197",
        "IonizationEnergy": "8417",
        "ElectronAffinity": "1.9",
        "StandardState": "Solid",
        "MeltingPoint": "527",
        "BoilingPoint": "1235",
        "Density": "9.32",
        "YearDiscovered": "1898"
    },
    {
        "AtomicNumber": "85",
        "Symbol": "At",
        "Name_es": "Astato",
        "Name_en": "Astatine",
        "OxidationStates": "7, 5, 3, 1, -1",
        "GroupBlock": "Halogen",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "209.98715",
        "CPKHexColor": "754F45",
        "ElectronConfiguration": "[Xe]6s2 4f14 5d10 6p5",
        "Electronegativity": "2.2",
        "AtomicRadius": "202",
        "IonizationEnergy": "9.5",
        "ElectronAffinity": "2.8",
        "StandardState": "Solid",
        "MeltingPoint": "575",
        "BoilingPoint": "",
        "Density": "7",
        "YearDiscovered": "1940"
    },
    {
        "AtomicNumber": "86",
        "Symbol": "Rn",
        "Name_es": "Radón",
        "Name_en": "Radon",
        "OxidationStates": "0",
        "GroupBlock": "Noble gas",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "222.01758",
        "CPKHexColor": "428296",
        "ElectronConfiguration": "[Xe]6s2 4f14 5d10 6p6",
        "Electronegativity": "",
        "AtomicRadius": "220",
        "IonizationEnergy": "10745",
        "ElectronAffinity": "",
        "StandardState": "Gas",
        "MeltingPoint": "202",
        "BoilingPoint": "211.45",
        "Density": "0.00973",
        "YearDiscovered": "1900"
    },
    {
        "AtomicNumber": "87",
        "Symbol": "Fr",
        "Name_es": "Francio",
        "Name_en": "Francium",
        "OxidationStates": "1",
        "GroupBlock": "Alkali metal",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "223.01973",
        "CPKHexColor": "420066",
        "ElectronConfiguration": "[Rn]7s1",
        "Electronegativity": "0.7",
        "AtomicRadius": "348",
        "IonizationEnergy": "3.9",
        "ElectronAffinity": "0.47",
        "StandardState": "Solid",
        "MeltingPoint": "300",
        "BoilingPoint": "",
        "Density": "",
        "YearDiscovered": "1939"
    },
    {
        "AtomicNumber": "88",
        "Symbol": "Ra",
        "Name_es": "Radio",
        "Name_en": "Radium",
        "OxidationStates": "2",
        "GroupBlock": "Alkaline earth metal",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "226.02541",
        "CPKHexColor": "007D00",
        "ElectronConfiguration": "[Rn]7s2",
        "Electronegativity": "0.9",
        "AtomicRadius": "283",
        "IonizationEnergy": "5279",
        "ElectronAffinity": "",
        "StandardState": "Solid",
        "MeltingPoint": "973",
        "BoilingPoint": "1413",
        "Density": "5",
        "YearDiscovered": "1898"
    },
    {
        "AtomicNumber": "89",
        "Symbol": "Ac",
        "Name_es": "Actinio",
        "Name_en": "Actinium",
        "OxidationStates": "3",
        "GroupBlock": "Actinide",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "227.02775",
        "CPKHexColor": "70ABFA",
        "ElectronConfiguration": "[Rn]7s2 6d1",
        "Electronegativity": "1.1",
        "AtomicRadius": "260",
        "IonizationEnergy": "5.17",
        "ElectronAffinity": "",
        "StandardState": "Solid",
        "MeltingPoint": "1324",
        "BoilingPoint": "3471",
        "Density": "10.07",
        "YearDiscovered": "1899"
    },
    {
        "AtomicNumber": "90",
        "Symbol": "Th",
        "Name_es": "Torio",
        "Name_en": "Thorium",
        "OxidationStates": "4",
        "GroupBlock": "Actinide",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "232038",
        "CPKHexColor": "00BAFF",
        "ElectronConfiguration": "[Rn]7s2 6d2",
        "Electronegativity": "1.3",
        "AtomicRadius": "237",
        "IonizationEnergy": "6.08",
        "ElectronAffinity": "",
        "StandardState": "Solid",
        "MeltingPoint": "2023",
        "BoilingPoint": "5061",
        "Density": "11.72",
        "YearDiscovered": "1828"
    },
    {
        "AtomicNumber": "91",
        "Symbol": "Pa",
        "Name_es": "Protactinio",
        "Name_en": "Protactinium",
        "OxidationStates": "+5, +4",
        "GroupBlock": "Actinide",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "231.03588",
        "CPKHexColor": "00A1FF",
        "ElectronConfiguration": "[Rn]7s2 5f2 6d1",
        "Electronegativity": "1.5",
        "AtomicRadius": "243",
        "IonizationEnergy": "5.89",
        "ElectronAffinity": "",
        "StandardState": "Solid",
        "MeltingPoint": "1845",
        "BoilingPoint": "",
        "Density": "15.37",
        "YearDiscovered": "1913"
    },
    {
        "AtomicNumber": "92",
        "Symbol": "U",
        "Name_es": "Uranio",
        "Name_en": "Uranium",
        "OxidationStates": "+6, +5, +4, +3",
        "GroupBlock": "Actinide",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "238.0289",
        "CPKHexColor": "008FFF",
        "ElectronConfiguration": "[Rn]7s2 5f3 6d1",
        "Electronegativity": "1.38",
        "AtomicRadius": "240",
        "IonizationEnergy": "6194",
        "ElectronAffinity": "",
        "StandardState": "Solid",
        "MeltingPoint": "1408",
        "BoilingPoint": "4404",
        "Density": "18.95",
        "YearDiscovered": "1789"
    },
    {
        "AtomicNumber": "93",
        "Symbol": "Np",
        "Name_es": "Neptunio",
        "Name_en": "Neptunium",
        "OxidationStates": "+6, +5, +4, +3",
        "GroupBlock": "Actinide",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "237.048172",
        "CPKHexColor": "0080FF",
        "ElectronConfiguration": "[Rn]7s2 5f4 6d1",
        "Electronegativity": "1.36",
        "AtomicRadius": "221",
        "IonizationEnergy": "6266",
        "ElectronAffinity": "",
        "StandardState": "Solid",
        "MeltingPoint": "917",
        "BoilingPoint": "4175",
        "Density": "20.25",
        "YearDiscovered": "1940"
    },
    {
        "AtomicNumber": "94",
        "Symbol": "Pu",
        "Name_es": "Plutonio",
        "Name_en": "Plutonium",
        "OxidationStates": "+6, +5, +4, +3",
        "GroupBlock": "Actinide",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "244.06420",
        "CPKHexColor": "006BFF",
        "ElectronConfiguration": "[Rn]7s2 5f6",
        "Electronegativity": "1.28",
        "AtomicRadius": "243",
        "IonizationEnergy": "6.06",
        "ElectronAffinity": "",
        "StandardState": "Solid",
        "MeltingPoint": "913",
        "BoilingPoint": "3501",
        "Density": "19.84",
        "YearDiscovered": "1940"
    },
    {
        "AtomicNumber": "95",
        "Symbol": "Am",
        "Name_es": "Americio",
        "Name_en": "Americium",
        "OxidationStates": "+6, +5, +4, +3",
        "GroupBlock": "Actinide",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "243.061380",
        "CPKHexColor": "545CF2",
        "ElectronConfiguration": "[Rn]7s2 5f7",
        "Electronegativity": "1.3",
        "AtomicRadius": "244",
        "IonizationEnergy": "5993",
        "ElectronAffinity": "",
        "StandardState": "Solid",
        "MeltingPoint": "1449",
        "BoilingPoint": "2284",
        "Density": "13.69",
        "YearDiscovered": "1944"
    },
    {
        "AtomicNumber": "96",
        "Symbol": "Cm",
        "Name_es": "Curio",
        "Name_en": "Curium",
        "OxidationStates": "3",
        "GroupBlock": "Actinide",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "247.07035",
        "CPKHexColor": "785CE3",
        "ElectronConfiguration": "[Rn]7s2 5f7 6d1",
        "Electronegativity": "1.3",
        "AtomicRadius": "245",
        "IonizationEnergy": "6.02",
        "ElectronAffinity": "",
        "StandardState": "Solid",
        "MeltingPoint": "1618",
        "BoilingPoint": "3400",
        "Density": "13.51",
        "YearDiscovered": "1944"
    },
    {
        "AtomicNumber": "97",
        "Symbol": "Bk",
        "Name_es": "Berkelio",
        "Name_en": "Berkelium",
        "OxidationStates": "+4, +3",
        "GroupBlock": "Actinide",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "247.07031",
        "CPKHexColor": "8A4FE3",
        "ElectronConfiguration": "[Rn]7s2 5f9",
        "Electronegativity": "1.3",
        "AtomicRadius": "244",
        "IonizationEnergy": "6.23",
        "ElectronAffinity": "",
        "StandardState": "Solid",
        "MeltingPoint": "1323",
        "BoilingPoint": "",
        "Density": "14",
        "YearDiscovered": "1949"
    },
    {
        "AtomicNumber": "98",
        "Symbol": "Cf",
        "Name_es": "Californio",
        "Name_en": "Californium",
        "OxidationStates": "3",
        "GroupBlock": "Actinide",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "251.07959",
        "CPKHexColor": "A136D4",
        "ElectronConfiguration": "[Rn]7s2 5f10",
        "Electronegativity": "1.3",
        "AtomicRadius": "245",
        "IonizationEnergy": "6.30",
        "ElectronAffinity": "",
        "StandardState": "Solid",
        "MeltingPoint": "1173",
        "BoilingPoint": "",
        "Density": "",
        "YearDiscovered": "1950"
    },
    {
        "AtomicNumber": "99",
        "Symbol": "Es",
        "Name_es": "Einsteinio",
        "Name_en": "Einsteinium",
        "OxidationStates": "3",
        "GroupBlock": "Actinide",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "252.0830",
        "CPKHexColor": "B31FD4",
        "ElectronConfiguration": "[Rn]7s2 5f11",
        "Electronegativity": "1.3",
        "AtomicRadius": "245",
        "IonizationEnergy": "6.42",
        "ElectronAffinity": "",
        "StandardState": "Solid",
        "MeltingPoint": "1133",
        "BoilingPoint": "",
        "Density": "",
        "YearDiscovered": "1952"
    },
    {
        "AtomicNumber": "100",
        "Symbol": "Fm",
        "Name_es": "Fermio",
        "Name_en": "Fermium",
        "OxidationStates": "3",
        "GroupBlock": "Actinide",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "257.09511",
        "CPKHexColor": "B31FBA",
        "ElectronConfiguration": "[Rn] 5f12 7s2",
        "Electronegativity": "1.3",
        "AtomicRadius": "",
        "IonizationEnergy": "6.50",
        "ElectronAffinity": "",
        "StandardState": "Solid",
        "MeltingPoint": "1800",
        "BoilingPoint": "",
        "Density": "",
        "YearDiscovered": "1952"
    },
    {
        "AtomicNumber": "101",
        "Symbol": "Md",
        "Name_es": "Mendelevio",
        "Name_en": "Mendelevium",
        "OxidationStates": "+3, +2",
        "GroupBlock": "Actinide",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "258.09843",
        "CPKHexColor": "B30DA6",
        "ElectronConfiguration": "[Rn]7s2 5f13",
        "Electronegativity": "1.3",
        "AtomicRadius": "",
        "IonizationEnergy": "6.58",
        "ElectronAffinity": "",
        "StandardState": "Solid",
        "MeltingPoint": "1100",
        "BoilingPoint": "",
        "Density": "",
        "YearDiscovered": "1955"
    },
    {
        "AtomicNumber": "102",
        "Symbol": "No",
        "Name_es": "Nobelio",
        "Name_en": "Nobelium",
        "OxidationStates": "+3, +2",
        "GroupBlock": "Actinide",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "259.10100",
        "CPKHexColor": "BD0D87",
        "ElectronConfiguration": "[Rn]7s2 5f14",
        "Electronegativity": "1.3",
        "AtomicRadius": "",
        "IonizationEnergy": "6.65",
        "ElectronAffinity": "",
        "StandardState": "Solid",
        "MeltingPoint": "1100",
        "BoilingPoint": "",
        "Density": "",
        "YearDiscovered": "1957"
    },
    {
        "AtomicNumber": "103",
        "Symbol": "Lr",
        "Name_es": "Laurencio",
        "Name_en": "Lawrencium",
        "OxidationStates": "3",
        "GroupBlock": "Actinide",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "266120",
        "CPKHexColor": "C70066",
        "ElectronConfiguration": "[Rn]7s2 5f14 6d1",
        "Electronegativity": "1.3",
        "AtomicRadius": "",
        "IonizationEnergy": "",
        "ElectronAffinity": "",
        "StandardState": "Solid",
        "MeltingPoint": "1900",
        "BoilingPoint": "",
        "Density": "",
        "YearDiscovered": "1961"
    },
    {
        "AtomicNumber": "104",
        "Symbol": "Rf",
        "Name_es": "Rutherfordio",
        "Name_en": "Rutherfordium",
        "OxidationStates": "4",
        "GroupBlock": "Transition metal",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "267122",
        "CPKHexColor": "CC0059",
        "ElectronConfiguration": "[Rn]7s2 5f14 6d2",
        "Electronegativity": "",
        "AtomicRadius": "",
        "IonizationEnergy": "",
        "ElectronAffinity": "",
        "StandardState": "Solid",
        "MeltingPoint": "",
        "BoilingPoint": "",
        "Density": "",
        "YearDiscovered": "1964"
    },
    {
        "AtomicNumber": "105",
        "Symbol": "Db",
        "Name_es": "Dubnio",
        "Name_en": "Dubnium",
        "OxidationStates": "5, 4, 3",
        "GroupBlock": "Transition metal",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "268126",
        "CPKHexColor": "D1004F",
        "ElectronConfiguration": "[Rn]7s2 5f14 6d3",
        "Electronegativity": "",
        "AtomicRadius": "",
        "IonizationEnergy": "",
        "ElectronAffinity": "",
        "StandardState": "Solid",
        "MeltingPoint": "",
        "BoilingPoint": "",
        "Density": "",
        "YearDiscovered": "1967"
    },
    {
        "AtomicNumber": "106",
        "Symbol": "Sg",
        "Name_es": "Seaborgio",
        "Name_en": "Seaborgium",
        "OxidationStates": "6, 5, 4, 3, 0",
        "GroupBlock": "Transition metal",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "269128",
        "CPKHexColor": "D90045",
        "ElectronConfiguration": "[Rn]7s2 5f14 6d4",
        "Electronegativity": "",
        "AtomicRadius": "",
        "IonizationEnergy": "",
        "ElectronAffinity": "",
        "StandardState": "Solid",
        "MeltingPoint": "",
        "BoilingPoint": "",
        "Density": "",
        "YearDiscovered": "1974"
    },
    {
        "AtomicNumber": "107",
        "Symbol": "Bh",
        "Name_es": "Bohrio",
        "Name_en": "Bohrium",
        "OxidationStates": "7, 5, 4, 3",
        "GroupBlock": "Transition metal",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "270133",
        "CPKHexColor": "E00038",
        "ElectronConfiguration": "[Rn]7s2 5f14 6d5",
        "Electronegativity": "",
        "AtomicRadius": "",
        "IonizationEnergy": "",
        "ElectronAffinity": "",
        "StandardState": "Solid",
        "MeltingPoint": "",
        "BoilingPoint": "",
        "Density": "",
        "YearDiscovered": "1976"
    },
    {
        "AtomicNumber": "108",
        "Symbol": "Hs",
        "Name_es": "Hassio",
        "Name_en": "Hassium",
        "OxidationStates": "8, 6, 5, 4, 3, 2",
        "GroupBlock": "Transition metal",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "269.1336",
        "CPKHexColor": "E6002E",
        "ElectronConfiguration": "[Rn]7s2 5f14 6d6",
        "Electronegativity": "",
        "AtomicRadius": "",
        "IonizationEnergy": "",
        "ElectronAffinity": "",
        "StandardState": "Solid",
        "MeltingPoint": "",
        "BoilingPoint": "",
        "Density": "",
        "YearDiscovered": "1984"
    },
    {
        "AtomicNumber": "109",
        "Symbol": "Mt",
        "Name_es": "Meitnerio",
        "Name_en": "Meitnerium",
        "OxidationStates": "9, 8, 6, 4, 3, 1",
        "GroupBlock": "Transition metal",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "277154",
        "CPKHexColor": "EB0026",
        "ElectronConfiguration": "[Rn]7s2 5f14 6d7 (calculated)",
        "Electronegativity": "",
        "AtomicRadius": "",
        "IonizationEnergy": "",
        "ElectronAffinity": "",
        "StandardState": "Solid",
        "MeltingPoint": "",
        "BoilingPoint": "",
        "Density": "",
        "YearDiscovered": "1982"
    },
    {
        "AtomicNumber": "110",
        "Symbol": "Ds",
        "Name_es": "Darmstadtio",
        "Name_en": "Darmstadtium",
        "OxidationStates": "8, 6, 4, 2, 0",
        "GroupBlock": "Transition metal",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "282166",
        "CPKHexColor": "",
        "ElectronConfiguration": "[Rn]7s2 5f14 6d8 (predicted)",
        "Electronegativity": "",
        "AtomicRadius": "",
        "IonizationEnergy": "",
        "ElectronAffinity": "",
        "StandardState": "Expected to be a Solid",
        "MeltingPoint": "",
        "BoilingPoint": "",
        "Density": "",
        "YearDiscovered": "1994"
    },
    {
        "AtomicNumber": "111",
        "Symbol": "Rg",
        "Name_es": "Roentgenio",
        "Name_en": "Roentgenium",
        "OxidationStates": "5, 3, 1, -1",
        "GroupBlock": "Transition metal",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "282169",
        "CPKHexColor": "",
        "ElectronConfiguration": "[Rn]7s2 5f14 6d9 (predicted)",
        "Electronegativity": "",
        "AtomicRadius": "",
        "IonizationEnergy": "",
        "ElectronAffinity": "",
        "StandardState": "Expected to be a Solid",
        "MeltingPoint": "",
        "BoilingPoint": "",
        "Density": "",
        "YearDiscovered": "1994"
    },
    {
        "AtomicNumber": "112",
        "Symbol": "Cn",
        "Name_es": "Copernicio",
        "Name_en": "Copernicium",
        "OxidationStates": "2, 1, 0",
        "GroupBlock": "Transition metal",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "286179",
        "CPKHexColor": "",
        "ElectronConfiguration": "[Rn]7s2 5f14 6d10 (predicted)",
        "Electronegativity": "",
        "AtomicRadius": "",
        "IonizationEnergy": "",
        "ElectronAffinity": "",
        "StandardState": "Expected to be a Solid",
        "MeltingPoint": "",
        "BoilingPoint": "",
        "Density": "",
        "YearDiscovered": "1996"
    },
    {
        "AtomicNumber": "113",
        "Symbol": "Nh",
        "Name_es": "Nihonio",
        "Name_en": "Nihonium",
        "OxidationStates": "",
        "GroupBlock": "Post-transition metal",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "286182",
        "CPKHexColor": "",
        "ElectronConfiguration": "[Rn]5f14 6d10 7s2 7p1 (predicted)",
        "Electronegativity": "",
        "AtomicRadius": "",
        "IonizationEnergy": "",
        "ElectronAffinity": "",
        "StandardState": "Expected to be a Solid",
        "MeltingPoint": "",
        "BoilingPoint": "",
        "Density": "",
        "YearDiscovered": "2004"
    },
    {
        "AtomicNumber": "114",
        "Symbol": "Fl",
        "Name_es": "Flerovio",
        "Name_en": "Flerovium",
        "OxidationStates": "6, 4,2, 1, 0",
        "GroupBlock": "Post-transition metal",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "290192",
        "CPKHexColor": "",
        "ElectronConfiguration": "[Rn]7s2 7p2 5f14 6d10 (predicted)",
        "Electronegativity": "",
        "AtomicRadius": "",
        "IonizationEnergy": "",
        "ElectronAffinity": "",
        "StandardState": "Expected to be a Solid",
        "MeltingPoint": "",
        "BoilingPoint": "",
        "Density": "",
        "YearDiscovered": "1998"
    },
    {
        "AtomicNumber": "115",
        "Symbol": "Mc",
        "Name_es": "Moscovio",
        "Name_en": "Moscovium",
        "OxidationStates": "3, 1",
        "GroupBlock": "Post-transition metal",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "290196",
        "CPKHexColor": "",
        "ElectronConfiguration": "[Rn]7s2 7p3 5f14 6d10 (predicted)",
        "Electronegativity": "",
        "AtomicRadius": "",
        "IonizationEnergy": "",
        "ElectronAffinity": "",
        "StandardState": "Expected to be a Solid",
        "MeltingPoint": "",
        "BoilingPoint": "",
        "Density": "",
        "YearDiscovered": "2003"
    },
    {
        "AtomicNumber": "116",
        "Symbol": "Lv",
        "Name_es": "Livermorio",
        "Name_en": "Livermorium",
        "OxidationStates": "+4, +2, -2",
        "GroupBlock": "Post-transition metal",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "293205",
        "CPKHexColor": "",
        "ElectronConfiguration": "[Rn]7s2 7p4 5f14 6d10 (predicted)",
        "Electronegativity": "",
        "AtomicRadius": "",
        "IonizationEnergy": "",
        "ElectronAffinity": "",
        "StandardState": "Expected to be a Solid",
        "MeltingPoint": "",
        "BoilingPoint": "",
        "Density": "",
        "YearDiscovered": "2000"
    },
    {
        "AtomicNumber": "117",
        "Symbol": "Ts",
        "Name_es": "Teneso",
        "Name_en": "Tennessine",
        "OxidationStates": "+5, +3, +1, -1",
        "GroupBlock": "Halogen",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "294211",
        "CPKHexColor": "",
        "ElectronConfiguration": "[Rn]7s2 7p5 5f14 6d10 (predicted)",
        "Electronegativity": "",
        "AtomicRadius": "",
        "IonizationEnergy": "",
        "ElectronAffinity": "",
        "StandardState": "Expected to be a Solid",
        "MeltingPoint": "",
        "BoilingPoint": "",
        "Density": "",
        "YearDiscovered": "2010"
    },
    {
        "AtomicNumber": "118",
        "Symbol": "Og",
        "Name_es": "Oganesón",
        "Name_en": "Oganesson",
        "OxidationStates": "+6, +4, +2, +1, 0, -1",
        "GroupBlock": "Noble gas",
        "subst_elem_subindex": "?",
        "": "",
        "AtomicMass": "295216",
        "CPKHexColor": "",
        "ElectronConfiguration": "[Rn]7s2 7p6 5f14 6d10 (predicted)",
        "Electronegativity": "",
        "AtomicRadius": "",
        "IonizationEnergy": "",
        "ElectronAffinity": "",
        "StandardState": "Expected to be a Gas",
        "MeltingPoint": "",
        "BoilingPoint": "",
        "Density": "",
        "YearDiscovered": "2006"
    }
];