const ELEMENTS = [
    {
        "name_ca": "Hidrogen",
        "name_es": "Hidrógeno",
        "symb": "H",
        "Z": "1",
        "A": "1,008",
        "kind": "no-metall",
        "nox": "–1/+1",
        "order_en_nm": "11",
        "apostrof": true,
        "stem_ca": "Hidr",
        "stem_es": "Hidr"
    },
    {
        "name_ca": "Heli",
        "name_es": "Helio",
        "symb": "He",
        "Z": "2",
        "A": "4,0026",
        "kind": "gas noble",
        "nox": "0",
        "order_en_nm": "",
        "apostrof": true,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Liti",
        "name_es": "Litio",
        "symb": "Li",
        "Z": "3",
        "A": "6,94",
        "kind": "metall",
        "nox": "+1",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Beril·li",
        "name_es": "Berilio",
        "symb": "Be",
        "Z": "4",
        "A": "9,0122",
        "kind": "metall",
        "nox": "+2",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Bor",
        "name_es": "Boro",
        "symb": "B",
        "Z": "5",
        "A": "10,81",
        "kind": "metal·loide",
        "nox": "+3",
        "order_en_nm": "22",
        "apostrof": false,
        "stem_ca": "Bor",
        "stem_es": "Bor"
    },
    {
        "name_ca": "Carboni",
        "name_es": "Carbono",
        "symb": "C",
        "Z": "6",
        "A": "12,011",
        "kind": "no-metall",
        "nox": "–4/+2/+4",
        "order_en_nm": "17",
        "apostrof": false,
        "stem_ca": "Carb",
        "stem_es": "Carb"
    },
    {
        "name_ca": "Nitrogen",
        "name_es": "Nitrógeno",
        "symb": "N",
        "Z": "7",
        "A": "14,007",
        "kind": "no-metall",
        "nox": "–3/+3/+5",
        "order_en_nm": "12",
        "apostrof": false,
        "stem_ca": "Nitr",
        "stem_es": "Nitr"
    },
    {
        "name_ca": "Oxigen",
        "name_es": "Oxígeno",
        "symb": "O",
        "Z": "8",
        "A": "15,999",
        "kind": "no-metall",
        "nox": "–2",
        "order_en_nm": "6",
        "apostrof": true,
        "stem_ca": "-",
        "stem_es": "-"
    },
    {
        "name_ca": "Fluor",
        "name_es": "Flúor",
        "symb": "F",
        "Z": "9",
        "A": "18,998",
        "kind": "no-metall",
        "nox": "–1",
        "order_en_nm": "1",
        "apostrof": false,
        "stem_ca": "Fluor",
        "stem_es": "Fluor"
    },
    {
        "name_ca": "Neó",
        "name_es": "Neón",
        "symb": "Ne",
        "Z": "10",
        "A": "20,18",
        "kind": "gas noble",
        "nox": "0",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Sodi",
        "name_es": "Sodio",
        "symb": "Na",
        "Z": "11",
        "A": "22,99",
        "kind": "metall",
        "nox": "+1",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Magnesi",
        "name_es": "Magnesio",
        "symb": "Mg",
        "Z": "12",
        "A": "24,305",
        "kind": "metall",
        "nox": "+2",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Alumini",
        "name_es": "Aluminio",
        "symb": "Al",
        "Z": "13",
        "A": "26,982",
        "kind": "metall",
        "nox": "+3",
        "order_en_nm": "23",
        "apostrof": true,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Silici",
        "name_es": "Silicio",
        "symb": "Si",
        "Z": "14",
        "A": "28,085",
        "kind": "metal·loide",
        "nox": "–4/+4",
        "order_en_nm": "18",
        "apostrof": false,
        "stem_ca": "Silic",
        "stem_es": "Silic"
    },
    {
        "name_ca": "Fòsfor",
        "name_es": "Fósforo",
        "symb": "P",
        "Z": "15",
        "A": "30,974",
        "kind": "no-metall",
        "nox": "–3/+3/+5",
        "order_en_nm": "13",
        "apostrof": false,
        "stem_ca": "Fosf",
        "stem_es": "Fosf"
    },
    {
        "name_ca": "Sofre",
        "name_es": "Azufre",
        "symb": "S",
        "Z": "16",
        "A": "32,06",
        "kind": "no-metall",
        "nox": "–2/+2/+4/+6",
        "order_en_nm": "7",
        "apostrof": false,
        "stem_ca": "Sulf",
        "stem_es": "Sulf"
    },
    {
        "name_ca": "Clor",
        "name_es": "Cloro",
        "symb": "Cl",
        "Z": "17",
        "A": "35,45",
        "kind": "no-metall",
        "nox": "–1/+1/+3/+5/+7",
        "order_en_nm": "2",
        "apostrof": false,
        "stem_ca": "Clor",
        "stem_es": "Clor"
    },
    {
        "name_ca": "Argó",
        "name_es": "Argón",
        "symb": "Ar",
        "Z": "18",
        "A": "39,95",
        "kind": "gas noble",
        "nox": "0",
        "order_en_nm": "",
        "apostrof": true,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Potassi",
        "name_es": "Potasio",
        "symb": "K",
        "Z": "19",
        "A": "39,098",
        "kind": "metall",
        "nox": "+1",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Calci",
        "name_es": "Calcio",
        "symb": "Ca",
        "Z": "20",
        "A": "40,078",
        "kind": "metall",
        "nox": "+2",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Escandi",
        "name_es": "Escandio",
        "symb": "Sc",
        "Z": "21",
        "A": "44,956",
        "kind": "metall",
        "nox": "+3",
        "order_en_nm": "",
        "apostrof": true,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Titani",
        "name_es": "Titanio",
        "symb": "Ti",
        "Z": "22",
        "A": "47,867",
        "kind": "metall",
        "nox": "+3/+4",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Vanadi",
        "name_es": "Vanadio",
        "symb": "V",
        "Z": "23",
        "A": "50,942",
        "kind": "metall",
        "nox": "+2/+3/+4/+5",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Crom",
        "name_es": "Cromo",
        "symb": "Cr",
        "Z": "24",
        "A": "51,996",
        "kind": "metall",
        "nox": "+2/+3/+6",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Manganès",
        "name_es": "Manganeso",
        "symb": "Mn",
        "Z": "25",
        "A": "54,938",
        "kind": "metall",
        "nox": "+2/+3/+4/+6/+7",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Ferro",
        "name_es": "Hierro",
        "symb": "Fe",
        "Z": "26",
        "A": "55,845",
        "kind": "metall",
        "nox": "+2/+3",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Cobalt",
        "name_es": "Cobalto",
        "symb": "Co",
        "Z": "27",
        "A": "58,933",
        "kind": "metall",
        "nox": "+2/+3",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Níquel",
        "name_es": "Níquel",
        "symb": "Ni",
        "Z": "28",
        "A": "58,693",
        "kind": "metall",
        "nox": "+2/+3",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Coure",
        "name_es": "Cobre",
        "symb": "Cu",
        "Z": "29",
        "A": "63,546",
        "kind": "metall",
        "nox": "+1/+2",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Zinc",
        "name_es": "Zinc / Cinc",
        "symb": "Zn",
        "Z": "30",
        "A": "65,38",
        "kind": "metall",
        "nox": "+2",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Gal·li",
        "name_es": "Galio",
        "symb": "Ga",
        "Z": "31",
        "A": "69,723",
        "kind": "metall",
        "nox": "+3",
        "order_en_nm": "24",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Germani",
        "name_es": "Germanio",
        "symb": "Ge",
        "Z": "32",
        "A": "72,63",
        "kind": "metal·loide",
        "nox": "+2/+4",
        "order_en_nm": "19",
        "apostrof": false,
        "stem_ca": "Germ",
        "stem_es": "Germ"
    },
    {
        "name_ca": "Arsènic / Arseni",
        "name_es": "Arsénico",
        "symb": "As",
        "Z": "33",
        "A": "74,922",
        "kind": "metal·loide",
        "nox": "–3/+3/+5",
        "order_en_nm": "14",
        "apostrof": true,
        "stem_ca": "Arsen",
        "stem_es": "Arsen"
    },
    {
        "name_ca": "Seleni",
        "name_es": "Selenio",
        "symb": "Se",
        "Z": "34",
        "A": "78,971",
        "kind": "no-metall",
        "nox": "–2/+2/+4/+6",
        "order_en_nm": "8",
        "apostrof": false,
        "stem_ca": "Selen",
        "stem_es": "Selen"
    },
    {
        "name_ca": "Brom",
        "name_es": "Bromo",
        "symb": "Br",
        "Z": "35",
        "A": "79,904",
        "kind": "no-metall",
        "nox": "–1/+1/+3/+5/+7",
        "order_en_nm": "3",
        "apostrof": false,
        "stem_ca": "Brom",
        "stem_es": "Brom"
    },
    {
        "name_ca": "Criptó",
        "name_es": "Kriptón",
        "symb": "Kr",
        "Z": "36",
        "A": "83,798",
        "kind": "gas noble",
        "nox": "0",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Rubidi",
        "name_es": "Rubidio",
        "symb": "Rb",
        "Z": "37",
        "A": "85,468",
        "kind": "metall",
        "nox": "+1",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Estronci",
        "name_es": "Estroncio",
        "symb": "Sr",
        "Z": "38",
        "A": "87,62",
        "kind": "metall",
        "nox": "+2",
        "order_en_nm": "",
        "apostrof": true,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Itri",
        "name_es": "Itrio",
        "symb": "Y",
        "Z": "39",
        "A": "88,906",
        "kind": "metall",
        "nox": "+3",
        "order_en_nm": "",
        "apostrof": true,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Zirconi",
        "name_es": "Circonio",
        "symb": "Zr",
        "Z": "40",
        "A": "91,224",
        "kind": "metall",
        "nox": "+4",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Niobi",
        "name_es": "Niobio",
        "symb": "Nb",
        "Z": "41",
        "A": "92,906",
        "kind": "metall",
        "nox": "+3/+5",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Molibdè",
        "name_es": "Molibdeno",
        "symb": "Mo",
        "Z": "42",
        "A": "95,95",
        "kind": "metall",
        "nox": "+4/+5/+6",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Tecneci",
        "name_es": "Tecnecio",
        "symb": "Tc",
        "Z": "43",
        "A": "-97",
        "kind": "metall",
        "nox": "+6/+7",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Ruteni",
        "name_es": "Rutenio",
        "symb": "Ru",
        "Z": "44",
        "A": "101,07",
        "kind": "metall",
        "nox": "+3/+4/+6",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Rodi",
        "name_es": "Rodio",
        "symb": "Rh",
        "Z": "45",
        "A": "102,91",
        "kind": "metall",
        "nox": "+1/+3/+4",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Pal·ladi",
        "name_es": "Paladio",
        "symb": "Pd",
        "Z": "46",
        "A": "106,42",
        "kind": "metall",
        "nox": "+2/+4",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Plata / Argent",
        "name_es": "Plata",
        "symb": "Ag",
        "Z": "47",
        "A": "107,87",
        "kind": "metall",
        "nox": "+1",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Cadmi",
        "name_es": "Cadmio",
        "symb": "Cd",
        "Z": "48",
        "A": "112,41",
        "kind": "metall",
        "nox": "+2",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Indi",
        "name_es": "Indio",
        "symb": "In",
        "Z": "49",
        "A": "114,82",
        "kind": "metall",
        "nox": "+3",
        "order_en_nm": "25",
        "apostrof": true,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Estany",
        "name_es": "Estaño",
        "symb": "Sn",
        "Z": "50",
        "A": "118,71",
        "kind": "metall",
        "nox": "+2/+4",
        "order_en_nm": "20",
        "apostrof": true,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Antimoni",
        "name_es": "Antimonio",
        "symb": "Sb",
        "Z": "51",
        "A": "121,76",
        "kind": "metal·loide",
        "nox": "–3/+3/+5",
        "order_en_nm": "15",
        "apostrof": true,
        "stem_ca": "Antimon",
        "stem_es": "Antimon"
    },
    {
        "name_ca": "Tel·luri / Tel·lur",
        "name_es": "Telurio",
        "symb": "Te",
        "Z": "52",
        "A": "127,6",
        "kind": "metal·loide",
        "nox": "–2/+2/+4/+6",
        "order_en_nm": "9",
        "apostrof": false,
        "stem_ca": "Tel·lur",
        "stem_es": "Telur"
    },
    {
        "name_ca": "Iode",
        "name_es": "Yodo",
        "symb": "I",
        "Z": "53",
        "A": "126,9",
        "kind": "no-metall",
        "nox": "–1/+1/+3/+5/+7",
        "order_en_nm": "4",
        "apostrof": false,
        "stem_ca": "Iod",
        "stem_es": "Yod"
    },
    {
        "name_ca": "Xenó",
        "name_es": "Xenón",
        "symb": "Xe",
        "Z": "54",
        "A": "131,29",
        "kind": "gas noble",
        "nox": "0/+2/+4/+6",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Cesi",
        "name_es": "Cesio",
        "symb": "Cs",
        "Z": "55",
        "A": "132,91",
        "kind": "metall",
        "nox": "+1",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Bari",
        "name_es": "Bario",
        "symb": "Ba",
        "Z": "56",
        "A": "137,33",
        "kind": "metall",
        "nox": "+2",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Lantani / Lantà",
        "name_es": "Lantano",
        "symb": "La",
        "Z": "57",
        "A": "138,91",
        "kind": "metall",
        "nox": "+3",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Ceri",
        "name_es": "Cerio",
        "symb": "Ce",
        "Z": "58",
        "A": "140,12",
        "kind": "metall",
        "nox": "+3/+4",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Praseodimi",
        "name_es": "Praseodimio",
        "symb": "Pr",
        "Z": "59",
        "A": "140,91",
        "kind": "metall",
        "nox": "+3",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Neodimi",
        "name_es": "Neodimio",
        "symb": "Nd",
        "Z": "60",
        "A": "144,24",
        "kind": "metall",
        "nox": "+3",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Prometi",
        "name_es": "Prometio",
        "symb": "Pm",
        "Z": "61",
        "A": "-145",
        "kind": "metall",
        "nox": "+3",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Samari",
        "name_es": "Samario",
        "symb": "Sm",
        "Z": "62",
        "A": "150,36",
        "kind": "metall",
        "nox": "+2/+3",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Europi",
        "name_es": "Europio",
        "symb": "Eu",
        "Z": "63",
        "A": "151,96",
        "kind": "metall",
        "nox": "+2/+3",
        "order_en_nm": "",
        "apostrof": true,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Gadolini",
        "name_es": "Gadolinio",
        "symb": "Gd",
        "Z": "64",
        "A": "157,25",
        "kind": "metall",
        "nox": "+3",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Terbi",
        "name_es": "Terbio",
        "symb": "Tb",
        "Z": "65",
        "A": "158,93",
        "kind": "metall",
        "nox": "+3",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Disprosi",
        "name_es": "Disprosio",
        "symb": "Dy",
        "Z": "66",
        "A": "162,5",
        "kind": "metall",
        "nox": "+3",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Holmi",
        "name_es": "Holmio",
        "symb": "Ho",
        "Z": "67",
        "A": "164,93",
        "kind": "metall",
        "nox": "+3",
        "order_en_nm": "",
        "apostrof": true,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Erbi",
        "name_es": "Erbio",
        "symb": "Er",
        "Z": "68",
        "A": "167,26",
        "kind": "metall",
        "nox": "+3",
        "order_en_nm": "",
        "apostrof": true,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Tuli",
        "name_es": "Tulio",
        "symb": "Tm",
        "Z": "69",
        "A": "168,93",
        "kind": "metall",
        "nox": "+3",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Iterbi",
        "name_es": "Iterbio",
        "symb": "Yb",
        "Z": "70",
        "A": "173,05",
        "kind": "metall",
        "nox": "+2/+3",
        "order_en_nm": "",
        "apostrof": true,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Luteci",
        "name_es": "Lutecio",
        "symb": "Lu",
        "Z": "71",
        "A": "174,97",
        "kind": "metall",
        "nox": "+3",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Hafni",
        "name_es": "Hafnio",
        "symb": "Hf",
        "Z": "72",
        "A": "178,49",
        "kind": "metall",
        "nox": "+4",
        "order_en_nm": "",
        "apostrof": true,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Tàntal",
        "name_es": "Tántalo",
        "symb": "Ta",
        "Z": "73",
        "A": "180,95",
        "kind": "metall",
        "nox": "+5",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Tungstè / Wolframi",
        "name_es": "Wolframio",
        "symb": "W",
        "Z": "74",
        "A": "183,84",
        "kind": "metall",
        "nox": "+4/+5/+6",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Reni",
        "name_es": "Renio",
        "symb": "Re",
        "Z": "75",
        "A": "186,21",
        "kind": "metall",
        "nox": "+4/+6/+7",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Osmi",
        "name_es": "Osmio",
        "symb": "Os",
        "Z": "76",
        "A": "190,23",
        "kind": "metall",
        "nox": "+4/+6/+8",
        "order_en_nm": "",
        "apostrof": true,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Iridi",
        "name_es": "Iridio",
        "symb": "Ir",
        "Z": "77",
        "A": "192,22",
        "kind": "metall",
        "nox": "+1/+3/+4",
        "order_en_nm": "",
        "apostrof": true,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Platí",
        "name_es": "Platino",
        "symb": "Pt",
        "Z": "78",
        "A": "195,08",
        "kind": "metall",
        "nox": "+2/+4",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Or",
        "name_es": "Oro",
        "symb": "Au",
        "Z": "79",
        "A": "196,97",
        "kind": "metall",
        "nox": "+1/+3",
        "order_en_nm": "",
        "apostrof": true,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Mercuri",
        "name_es": "Mercurio",
        "symb": "Hg",
        "Z": "80",
        "A": "200,59",
        "kind": "metall",
        "nox": "+1/+2",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Tal·li",
        "name_es": "Talio",
        "symb": "Tl",
        "Z": "81",
        "A": "204,38",
        "kind": "metall",
        "nox": "+1/+3",
        "order_en_nm": "26",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Plom",
        "name_es": "Plomo",
        "symb": "Pb",
        "Z": "82",
        "A": "207,2",
        "kind": "metall",
        "nox": "+2/+4",
        "order_en_nm": "21",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Bismut",
        "name_es": "Bismuto",
        "symb": "Bi",
        "Z": "83",
        "A": "208,98",
        "kind": "metall",
        "nox": "+3/+5",
        "order_en_nm": "16",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Poloni",
        "name_es": "Polonio",
        "symb": "Po",
        "Z": "84",
        "A": "-209",
        "kind": "metal·loide",
        "nox": "+2/+4",
        "order_en_nm": "10",
        "apostrof": false,
        "stem_ca": "Polon",
        "stem_es": "Polon"
    },
    {
        "name_ca": "Àstat",
        "name_es": "Astato",
        "symb": "At",
        "Z": "85",
        "A": "-210",
        "kind": "no-metall",
        "nox": "–1/+1",
        "order_en_nm": "5",
        "apostrof": false,
        "stem_ca": "Astat",
        "stem_es": "Astat"
    },
    {
        "name_ca": "Radó",
        "name_es": "Radón",
        "symb": "Rn",
        "Z": "86",
        "A": "-222",
        "kind": "gas noble",
        "nox": "0",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Franci",
        "name_es": "Francio",
        "symb": "Fr",
        "Z": "87",
        "A": "-223",
        "kind": "metall",
        "nox": "+1",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Radi",
        "name_es": "Radio",
        "symb": "Ra",
        "Z": "88",
        "A": "-226",
        "kind": "metall",
        "nox": "+2",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Actini",
        "name_es": "Actinio",
        "symb": "Ac",
        "Z": "89",
        "A": "-227",
        "kind": "metall",
        "nox": "+3",
        "order_en_nm": "",
        "apostrof": true,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Tori",
        "name_es": "Torio",
        "symb": "Th",
        "Z": "90",
        "A": "232,04",
        "kind": "metall",
        "nox": "+4",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Protoactini",
        "name_es": "Protactinio",
        "symb": "Pa",
        "Z": "91",
        "A": "231,04",
        "kind": "metall",
        "nox": "+3/+4/+5",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Urani",
        "name_es": "Uranio",
        "symb": "U",
        "Z": "92",
        "A": "238,03",
        "kind": "metall",
        "nox": "+3/+4/+5/+6",
        "order_en_nm": "",
        "apostrof": true,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Neptuni",
        "name_es": "Neptunio",
        "symb": "Np",
        "Z": "93",
        "A": "-237",
        "kind": "metall",
        "nox": "+3/+4/+5",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Plutoni",
        "name_es": "Plutonio",
        "symb": "Pu",
        "Z": "94",
        "A": "-244",
        "kind": "metall",
        "nox": "+3/+4/+5/+6",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Americi",
        "name_es": "Americio",
        "symb": "Am",
        "Z": "95",
        "A": "-243",
        "kind": "metall",
        "nox": "+3/+4/+5/+6",
        "order_en_nm": "",
        "apostrof": true,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Curi",
        "name_es": "Curio",
        "symb": "Cm",
        "Z": "96",
        "A": "-247",
        "kind": "metall",
        "nox": "+3",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Berkeli",
        "name_es": "Berkelio",
        "symb": "Bk",
        "Z": "97",
        "A": "-247",
        "kind": "metall",
        "nox": "+3/+4",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Californi",
        "name_es": "Californio",
        "symb": "Cf",
        "Z": "98",
        "A": "-251",
        "kind": "metall",
        "nox": "+3",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Einsteini",
        "name_es": "Einstenio",
        "symb": "Es",
        "Z": "99",
        "A": "-252",
        "kind": "metall",
        "nox": "+3",
        "order_en_nm": "",
        "apostrof": true,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Fermi",
        "name_es": "Fermio",
        "symb": "Fm",
        "Z": "100",
        "A": "-257",
        "kind": "metall",
        "nox": "+3",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Mendelevi",
        "name_es": "Mendelevio",
        "symb": "Md",
        "Z": "101",
        "A": "-258",
        "kind": "metall",
        "nox": "+3",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Nobeli",
        "name_es": "Nobelio",
        "symb": "No",
        "Z": "102",
        "A": "-259",
        "kind": "metall",
        "nox": "+3",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Lawrenci",
        "name_es": "Lawrencio",
        "symb": "Lr",
        "Z": "103",
        "A": "-266",
        "kind": "metall",
        "nox": "+3",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Rutherfordi",
        "name_es": "Rutherfordio",
        "symb": "Rf",
        "Z": "104",
        "A": "-267",
        "kind": "metall",
        "nox": "",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Dubni",
        "name_es": "Dubnio",
        "symb": "Db",
        "Z": "105",
        "A": "-268",
        "kind": "metall",
        "nox": "",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Seaborgi",
        "name_es": "Seaborgio",
        "symb": "Sg",
        "Z": "106",
        "A": "-269",
        "kind": "metall",
        "nox": "",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Bohri",
        "name_es": "Bohrio",
        "symb": "Bh",
        "Z": "107",
        "A": "-278",
        "kind": "metall",
        "nox": "",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Hassi",
        "name_es": "Hasio",
        "symb": "Hs",
        "Z": "108",
        "A": "-278",
        "kind": "metall",
        "nox": "",
        "order_en_nm": "",
        "apostrof": true,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Meitneri",
        "name_es": "Meitnerio",
        "symb": "Mt",
        "Z": "109",
        "A": "-282",
        "kind": "metall",
        "nox": "",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Darmstadti",
        "name_es": "Darmstatio",
        "symb": "Ds",
        "Z": "110",
        "A": "-282",
        "kind": "metall",
        "nox": "",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Roentgeni",
        "name_es": "Roentgenio",
        "symb": "Rg",
        "Z": "111",
        "A": "-286",
        "kind": "metall",
        "nox": "",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Copernici",
        "name_es": "Copernicio",
        "symb": "Cn",
        "Z": "112",
        "A": "-286",
        "kind": "metall",
        "nox": "",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Nihoni",
        "name_es": "Nihonio",
        "symb": "Nh",
        "Z": "113",
        "A": "-286",
        "kind": "metall",
        "nox": "",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Flerovi",
        "name_es": "Flerovio",
        "symb": "Fl",
        "Z": "114",
        "A": "-290",
        "kind": "metall",
        "nox": "",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Moscovi",
        "name_es": "Moscovio",
        "symb": "Mc",
        "Z": "115",
        "A": "-290",
        "kind": "metall",
        "nox": "",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Livermori",
        "name_es": "Livermorio",
        "symb": "Lv",
        "Z": "116",
        "A": "-293",
        "kind": "metall",
        "nox": "",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "name_ca": "Tennes",
        "name_es": "Teneso",
        "symb": "Ts",
        "Z": "117",
        "A": "-294",
        "kind": "no-metall",
        "nox": "",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "-",
        "stem_es": "-"
    },
    {
        "name_ca": "Oganessó",
        "name_es": "Oganesón",
        "symb": "Og",
        "Z": "118",
        "A": "-294",
        "kind": "gas noble",
        "nox": "",
        "order_en_nm": "",
        "apostrof": true,
        "stem_ca": "",
        "stem_es": ""
    },
    {
        "symb": "X",  // Usat per grup hidròxid.
    }
];
