"use strict";
export const ELEMENTS = [
    {
        "name_ca": "Hidrogen",
        "name_es": "Hidrógeno",
        "name_en": "Hydrogen",
        "name_eu": "Hidrogeno",
        "symb": "H",
        "Z": "1",
        "A": "1,008",
        "kind": "no-metall",
        "nox": "–1/+1",
        "order_en_nm": "11",
        "apostrof": true,
        "stem_ca": "Hidr",
        "stem_es": "Hidr",
        "stem_en": "Hydr",
        "stem_eu": "Hidr"
    },
    {
        "name_ca": "Heli",
        "name_es": "Helio",
        "name_en": "Helium",
        "name_eu": "Helio",
        "symb": "He",
        "Z": "2",
        "A": "4,0026",
        "kind": "gas noble",
        "nox": "0",
        "order_en_nm": "",
        "apostrof": true,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Liti",
        "name_es": "Litio",
        "name_en": "Lithium",
        "name_eu": "Litio",
        "symb": "Li",
        "Z": "3",
        "A": "6,94",
        "kind": "metall",
        "nox": "+1",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Beril·li",
        "name_es": "Berilio",
        "name_en": "Beryllium",
        "name_eu": "Berilio",
        "symb": "Be",
        "Z": "4",
        "A": "9,0122",
        "kind": "metall",
        "nox": "+2",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Bor",
        "name_es": "Boro",
        "name_en": "Boron",
        "name_eu": "Boro",
        "symb": "B",
        "Z": "5",
        "A": "10,81",
        "kind": "metal·loide",
        "nox": "+3",
        "order_en_nm": "22",
        "apostrof": false,
        "stem_ca": "Bor",
        "stem_es": "Bor",
        "stem_en": "Bor",
        "stem_eu": "Bor"
    },
    {
        "name_ca": "Carboni",
        "name_es": "Carbono",
        "name_en": "Carbon",
        "name_eu": "Karbono",
        "symb": "C",
        "Z": "6",
        "A": "12,011",
        "kind": "no-metall",
        "nox": "–4/+2/+4",
        "order_en_nm": "17",
        "apostrof": false,
        "stem_ca": "Carb",
        "stem_es": "Carb",
        "stem_en": "Carb",
        "stem_eu": "Karb"
    },
    {
        "name_ca": "Nitrogen",
        "name_es": "Nitrógeno",
        "name_en": "Nitrogen",
        "name_eu": "Nitrogeno",
        "symb": "N",
        "Z": "7",
        "A": "14,007",
        "kind": "no-metall",
        "nox": "–3/+3/+5",
        "order_en_nm": "12",
        "apostrof": false,
        "stem_ca": "Nitr",
        "stem_es": "Nitr",
        "stem_en": "Nitr",
        "stem_eu": "Nitr"
    },
    {
        "name_ca": "Oxigen",
        "name_es": "Oxígeno",
        "name_en": "Oxygen",
        "name_eu": "Oxigeno",
        "symb": "O",
        "Z": "8",
        "A": "15,999",
        "kind": "no-metall",
        "nox": "–2",
        "order_en_nm": "6",
        "apostrof": true,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Fluor",
        "name_es": "Flúor",
        "name_en": "Fluorine",
        "name_eu": "Fluor",
        "symb": "F",
        "Z": "9",
        "A": "18,998",
        "kind": "no-metall",
        "nox": "–1",
        "order_en_nm": "1",
        "apostrof": false,
        "stem_ca": "Fluor",
        "stem_es": "Fluor",
        "stem_en": "Fluor",
        "stem_eu": "Fluor"
    },
    {
        "name_ca": "Neó",
        "name_es": "Neón",
        "name_en": "Neon",
        "name_eu": "Neon",
        "symb": "Ne",
        "Z": "10",
        "A": "20,18",
        "kind": "gas noble",
        "nox": "0",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Sodi",
        "name_es": "Sodio",
        "name_en": "Sodium",
        "name_eu": "Sodio",
        "symb": "Na",
        "Z": "11",
        "A": "22,99",
        "kind": "metall",
        "nox": "+1",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Magnesi",
        "name_es": "Magnesio",
        "name_en": "Magnesium",
        "name_eu": "Magnesio",
        "symb": "Mg",
        "Z": "12",
        "A": "24,305",
        "kind": "metall",
        "nox": "+2",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Alumini",
        "name_es": "Aluminio",
        "name_en": "Aluminum / Aluminium",
        "name_eu": "Aluminio",
        "symb": "Al",
        "Z": "13",
        "A": "26,982",
        "kind": "metall",
        "nox": "+3",
        "order_en_nm": "23",
        "apostrof": true,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Silici",
        "name_es": "Silicio",
        "name_en": "Silicon",
        "name_eu": "Silizio",
        "symb": "Si",
        "Z": "14",
        "A": "28,085",
        "kind": "metal·loide",
        "nox": "–4/+4",
        "order_en_nm": "18",
        "apostrof": false,
        "stem_ca": "Silic",
        "stem_es": "Silic",
        "stem_en": "Silic",
        "stem_eu": "Siliz"
    },
    {
        "name_ca": "Fòsfor",
        "name_es": "Fósforo",
        "name_en": "Phosphorus",
        "name_eu": "Fosforo",
        "symb": "P",
        "Z": "15",
        "A": "30,974",
        "kind": "no-metall",
        "nox": "–3/+3/+5",
        "order_en_nm": "13",
        "apostrof": false,
        "stem_ca": "Fosf",
        "stem_es": "Fosf",
        "stem_en": "Phosph",
        "stem_eu": "Fost"
    },
    {
        "name_ca": "Sofre",
        "name_es": "Azufre",
        "name_en": "Sulfur",
        "name_eu": "Sufre",
        "symb": "S",
        "Z": "16",
        "A": "32,06",
        "kind": "no-metall",
        "nox": "–2/+2/+4/+6",
        "order_en_nm": "7",
        "apostrof": false,
        "stem_ca": "Sulf",
        "stem_es": "Sulf",
        "stem_en": "Sulf",
        "stem_eu": "Sulf"
    },
    {
        "name_ca": "Clor",
        "name_es": "Cloro",
        "name_en": "Chlorine",
        "name_eu": "Kloro",
        "symb": "Cl",
        "Z": "17",
        "A": "35,45",
        "kind": "no-metall",
        "nox": "–1/+1/+3/+5/+7",
        "order_en_nm": "2",
        "apostrof": false,
        "stem_ca": "Clor",
        "stem_es": "Clor",
        "stem_en": "Chlor",
        "stem_eu": "Klor"
    },
    {
        "name_ca": "Argó",
        "name_es": "Argón",
        "name_en": "Argon",
        "name_eu": "Argon",
        "symb": "Ar",
        "Z": "18",
        "A": "39,95",
        "kind": "gas noble",
        "nox": "0",
        "order_en_nm": "",
        "apostrof": true,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Potassi",
        "name_es": "Potasio",
        "name_en": "Potassium",
        "name_eu": "Potasio",
        "symb": "K",
        "Z": "19",
        "A": "39,098",
        "kind": "metall",
        "nox": "+1",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Calci",
        "name_es": "Calcio",
        "name_en": "Calcium",
        "name_eu": "Kaltzio",
        "symb": "Ca",
        "Z": "20",
        "A": "40,078",
        "kind": "metall",
        "nox": "+2",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Escandi",
        "name_es": "Escandio",
        "name_en": "Scandium",
        "name_eu": "Eskandio",
        "symb": "Sc",
        "Z": "21",
        "A": "44,956",
        "kind": "metall",
        "nox": "+3",
        "order_en_nm": "",
        "apostrof": true,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Titani",
        "name_es": "Titanio",
        "name_en": "Titanium",
        "name_eu": "Titanio",
        "symb": "Ti",
        "Z": "22",
        "A": "47,867",
        "kind": "metall",
        "nox": "+3/+4",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Vanadi",
        "name_es": "Vanadio",
        "name_en": "Vanadium",
        "name_eu": "Banadio",
        "symb": "V",
        "Z": "23",
        "A": "50,942",
        "kind": "metall",
        "nox": "+2/+3/+4/+5",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Crom",
        "name_es": "Cromo",
        "name_en": "Chromium",
        "name_eu": "Kromo",
        "symb": "Cr",
        "Z": "24",
        "A": "51,996",
        "kind": "metall",
        "nox": "+2/+3/+6",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Manganès",
        "name_es": "Manganeso",
        "name_en": "Manganese",
        "name_eu": "Manganeso",
        "symb": "Mn",
        "Z": "25",
        "A": "54,938",
        "kind": "metall",
        "nox": "+2/+3/+4/+6/+7",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Ferro",
        "name_es": "Hierro",
        "name_en": "Iron",
        "name_eu": "Burdin",
        "symb": "Fe",
        "Z": "26",
        "A": "55,845",
        "kind": "metall",
        "nox": "+2/+3",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Cobalt",
        "name_es": "Cobalto",
        "name_en": "Cobalt",
        "name_eu": "Kobalto",
        "symb": "Co",
        "Z": "27",
        "A": "58,933",
        "kind": "metall",
        "nox": "+2/+3",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Níquel",
        "name_es": "Níquel",
        "name_en": "Nickel",
        "name_eu": "Nikel",
        "symb": "Ni",
        "Z": "28",
        "A": "58,693",
        "kind": "metall",
        "nox": "+2/+3",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Coure",
        "name_es": "Cobre",
        "name_en": "Copper",
        "name_eu": "Kobre",
        "symb": "Cu",
        "Z": "29",
        "A": "63,546",
        "kind": "metall",
        "nox": "+1/+2",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Zinc",
        "name_es": "Zinc / Cinc",
        "name_en": "Zinc",
        "name_eu": "Zink",
        "symb": "Zn",
        "Z": "30",
        "A": "65,38",
        "kind": "metall",
        "nox": "+2",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Gal·li",
        "name_es": "Galio",
        "name_en": "Gallium",
        "name_eu": "Galio",
        "symb": "Ga",
        "Z": "31",
        "A": "69,723",
        "kind": "metall",
        "nox": "+3",
        "order_en_nm": "24",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Germani",
        "name_es": "Germanio",
        "name_en": "Germanium",
        "name_eu": "Germanio",
        "symb": "Ge",
        "Z": "32",
        "A": "72,63",
        "kind": "metal·loide",
        "nox": "+2/+4",
        "order_en_nm": "19",
        "apostrof": false,
        "stem_ca": "Germ",
        "stem_es": "Germ",
        "stem_en": "German",
        "stem_eu": "Germ"
    },
    {
        "name_ca": "Arsènic / Arseni",
        "name_es": "Arsénico",
        "name_en": "Arsenic",
        "name_eu": "Artseniko",
        "symb": "As",
        "Z": "33",
        "A": "74,922",
        "kind": "metal·loide",
        "nox": "–3/+3/+5",
        "order_en_nm": "14",
        "apostrof": true,
        "stem_ca": "Arsen",
        "stem_es": "Arsen",
        "stem_en": "Arsen",
        "stem_eu": "Artsen"
    },
    {
        "name_ca": "Seleni",
        "name_es": "Selenio",
        "name_en": "Selenium",
        "name_eu": "Selenio",
        "symb": "Se",
        "Z": "34",
        "A": "78,971",
        "kind": "no-metall",
        "nox": "–2/+2/+4/+6",
        "order_en_nm": "8",
        "apostrof": false,
        "stem_ca": "Selen",
        "stem_es": "Selen",
        "stem_en": "Selen",
        "stem_eu": "Selen"
    },
    {
        "name_ca": "Brom",
        "name_es": "Bromo",
        "name_en": "Bromine",
        "name_eu": "Bromo",
        "symb": "Br",
        "Z": "35",
        "A": "79,904",
        "kind": "no-metall",
        "nox": "–1/+1/+3/+5/+7",
        "order_en_nm": "3",
        "apostrof": false,
        "stem_ca": "Brom",
        "stem_es": "Brom",
        "stem_en": "Brom",
        "stem_eu": "Brom"
    },
    {
        "name_ca": "Criptó",
        "name_es": "Kriptón",
        "name_en": "Krypton",
        "name_eu": "Kripton",
        "symb": "Kr",
        "Z": "36",
        "A": "83,798",
        "kind": "gas noble",
        "nox": "0",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Rubidi",
        "name_es": "Rubidio",
        "name_en": "Rubidium",
        "name_eu": "Rubidio",
        "symb": "Rb",
        "Z": "37",
        "A": "85,468",
        "kind": "metall",
        "nox": "+1",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Estronci",
        "name_es": "Estroncio",
        "name_en": "Strontium",
        "name_eu": "Estrontzio",
        "symb": "Sr",
        "Z": "38",
        "A": "87,62",
        "kind": "metall",
        "nox": "+2",
        "order_en_nm": "",
        "apostrof": true,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Itri",
        "name_es": "Itrio",
        "name_en": "Yttrium",
        "name_eu": "Itrio",
        "symb": "Y",
        "Z": "39",
        "A": "88,906",
        "kind": "metall",
        "nox": "+3",
        "order_en_nm": "",
        "apostrof": true,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Zirconi",
        "name_es": "Circonio",
        "name_en": "Zirconium",
        "name_eu": "Zirkonio",
        "symb": "Zr",
        "Z": "40",
        "A": "91,224",
        "kind": "metall",
        "nox": "+4",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Niobi",
        "name_es": "Niobio",
        "name_en": "Niobium",
        "name_eu": "Niobio",
        "symb": "Nb",
        "Z": "41",
        "A": "92,906",
        "kind": "metall",
        "nox": "+3/+5",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Molibdè",
        "name_es": "Molibdeno",
        "name_en": "Molybdenum",
        "name_eu": "Molibdeno",
        "symb": "Mo",
        "Z": "42",
        "A": "95,95",
        "kind": "metall",
        "nox": "+4/+5/+6",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Tecneci",
        "name_es": "Tecnecio",
        "name_en": "Technetium",
        "name_eu": "Teknezio",
        "symb": "Tc",
        "Z": "43",
        "A": "-97",
        "kind": "metall",
        "nox": "+6/+7",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Ruteni",
        "name_es": "Rutenio",
        "name_en": "Ruthenium",
        "name_eu": "Rutenio",
        "symb": "Ru",
        "Z": "44",
        "A": "101,07",
        "kind": "metall",
        "nox": "+3/+4/+6",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Rodi",
        "name_es": "Rodio",
        "name_en": "Rhodium",
        "name_eu": "Rodio",
        "symb": "Rh",
        "Z": "45",
        "A": "102,91",
        "kind": "metall",
        "nox": "+1/+3/+4",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Pal·ladi",
        "name_es": "Paladio",
        "name_en": "Palladium",
        "name_eu": "Paladio",
        "symb": "Pd",
        "Z": "46",
        "A": "106,42",
        "kind": "metall",
        "nox": "+2/+4",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Plata / Argent",
        "name_es": "Plata",
        "name_en": "Silver",
        "name_eu": "Zilar",
        "symb": "Ag",
        "Z": "47",
        "A": "107,87",
        "kind": "metall",
        "nox": "+1",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Cadmi",
        "name_es": "Cadmio",
        "name_en": "Cadmium",
        "name_eu": "Kadmio",
        "symb": "Cd",
        "Z": "48",
        "A": "112,41",
        "kind": "metall",
        "nox": "+2",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Indi",
        "name_es": "Indio",
        "name_en": "Indium",
        "name_eu": "Indio",
        "symb": "In",
        "Z": "49",
        "A": "114,82",
        "kind": "metall",
        "nox": "+3",
        "order_en_nm": "25",
        "apostrof": true,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Estany",
        "name_es": "Estaño",
        "name_en": "Tin",
        "name_eu": "Eztainu",
        "symb": "Sn",
        "Z": "50",
        "A": "118,71",
        "kind": "metall",
        "nox": "+2/+4",
        "order_en_nm": "20",
        "apostrof": true,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Antimoni",
        "name_es": "Antimonio",
        "name_en": "Antimony",
        "name_eu": "Antimonio",
        "symb": "Sb",
        "Z": "51",
        "A": "121,76",
        "kind": "metal·loide",
        "nox": "–3/+3/+5",
        "order_en_nm": "15",
        "apostrof": true,
        "stem_ca": "Antimon",
        "stem_es": "Antimon",
        "stem_en": "Antimon",
        "stem_eu": "Antimon"
    },
    {
        "name_ca": "Tel·luri / Tel·lur",
        "name_es": "Telurio",
        "name_en": "Tellurium",
        "name_eu": "Telurio",
        "symb": "Te",
        "Z": "52",
        "A": "127,6",
        "kind": "metal·loide",
        "nox": "–2/+2/+4/+6",
        "order_en_nm": "9",
        "apostrof": false,
        "stem_ca": "Tel·lur",
        "stem_es": "Telur",
        "stem_en": "Tellur",
        "stem_eu": "Telur"
    },
    {
        "name_ca": "Iode",
        "name_es": "Yodo",
        "name_en": "Iodine",
        "name_eu": "Iodo",
        "symb": "I",
        "Z": "53",
        "A": "126,9",
        "kind": "no-metall",
        "nox": "–1/+1/+3/+5/+7",
        "order_en_nm": "4",
        "apostrof": false,
        "stem_ca": "Iod",
        "stem_es": "Yod",
        "stem_en": "Iod",
        "stem_eu": "Iod"
    },
    {
        "name_ca": "Xenó",
        "name_es": "Xenón",
        "name_en": "Xenon",
        "name_eu": "Xenon",
        "symb": "Xe",
        "Z": "54",
        "A": "131,29",
        "kind": "gas noble",
        "nox": "0/+2/+4/+6",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Cesi",
        "name_es": "Cesio",
        "name_en": "Cesium / Caesium",
        "name_eu": "Zesio",
        "symb": "Cs",
        "Z": "55",
        "A": "132,91",
        "kind": "metall",
        "nox": "+1",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Bari",
        "name_es": "Bario",
        "name_en": "Barium",
        "name_eu": "Bario",
        "symb": "Ba",
        "Z": "56",
        "A": "137,33",
        "kind": "metall",
        "nox": "+2",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Lantani / Lantà",
        "name_es": "Lantano",
        "name_en": "Lanthanum",
        "name_eu": "Lantano",
        "symb": "La",
        "Z": "57",
        "A": "138,91",
        "kind": "metall",
        "nox": "+3",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Ceri",
        "name_es": "Cerio",
        "name_en": "Cerium",
        "name_eu": "Zerio",
        "symb": "Ce",
        "Z": "58",
        "A": "140,12",
        "kind": "metall",
        "nox": "+3/+4",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Praseodimi",
        "name_es": "Praseodimio",
        "name_en": "Praseodymium",
        "name_eu": "Praseodimio",
        "symb": "Pr",
        "Z": "59",
        "A": "140,91",
        "kind": "metall",
        "nox": "+3",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Neodimi",
        "name_es": "Neodimio",
        "name_en": "Neodymium",
        "name_eu": "Neodimio",
        "symb": "Nd",
        "Z": "60",
        "A": "144,24",
        "kind": "metall",
        "nox": "+3",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Prometi",
        "name_es": "Prometio",
        "name_en": "Promethium",
        "name_eu": "Prometio",
        "symb": "Pm",
        "Z": "61",
        "A": "-145",
        "kind": "metall",
        "nox": "+3",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Samari",
        "name_es": "Samario",
        "name_en": "Samarium",
        "name_eu": "Samario",
        "symb": "Sm",
        "Z": "62",
        "A": "150,36",
        "kind": "metall",
        "nox": "+2/+3",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Europi",
        "name_es": "Europio",
        "name_en": "Europium",
        "name_eu": "Europio",
        "symb": "Eu",
        "Z": "63",
        "A": "151,96",
        "kind": "metall",
        "nox": "+2/+3",
        "order_en_nm": "",
        "apostrof": true,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Gadolini",
        "name_es": "Gadolinio",
        "name_en": "Gadolinium",
        "name_eu": "Gadolinio",
        "symb": "Gd",
        "Z": "64",
        "A": "157,25",
        "kind": "metall",
        "nox": "+3",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Terbi",
        "name_es": "Terbio",
        "name_en": "Terbium",
        "name_eu": "Terbio",
        "symb": "Tb",
        "Z": "65",
        "A": "158,93",
        "kind": "metall",
        "nox": "+3",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Disprosi",
        "name_es": "Disprosio",
        "name_en": "Dysprosium",
        "name_eu": "Disprosio",
        "symb": "Dy",
        "Z": "66",
        "A": "162,5",
        "kind": "metall",
        "nox": "+3",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Holmi",
        "name_es": "Holmio",
        "name_en": "Holmium",
        "name_eu": "Holmio",
        "symb": "Ho",
        "Z": "67",
        "A": "164,93",
        "kind": "metall",
        "nox": "+3",
        "order_en_nm": "",
        "apostrof": true,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Erbi",
        "name_es": "Erbio",
        "name_en": "Erbium",
        "name_eu": "Erbio",
        "symb": "Er",
        "Z": "68",
        "A": "167,26",
        "kind": "metall",
        "nox": "+3",
        "order_en_nm": "",
        "apostrof": true,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Tuli",
        "name_es": "Tulio",
        "name_en": "Thulium",
        "name_eu": "Tulio",
        "symb": "Tm",
        "Z": "69",
        "A": "168,93",
        "kind": "metall",
        "nox": "+3",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Iterbi",
        "name_es": "Iterbio",
        "name_en": "Ytterbium",
        "name_eu": "Iterbio",
        "symb": "Yb",
        "Z": "70",
        "A": "173,05",
        "kind": "metall",
        "nox": "+2/+3",
        "order_en_nm": "",
        "apostrof": true,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Luteci",
        "name_es": "Lutecio",
        "name_en": "Lutetium",
        "name_eu": "Lutezio",
        "symb": "Lu",
        "Z": "71",
        "A": "174,97",
        "kind": "metall",
        "nox": "+3",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Hafni",
        "name_es": "Hafnio",
        "name_en": "Hafnium",
        "name_eu": "Hafnio",
        "symb": "Hf",
        "Z": "72",
        "A": "178,49",
        "kind": "metall",
        "nox": "+4",
        "order_en_nm": "",
        "apostrof": true,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Tàntal",
        "name_es": "Tántalo",
        "name_en": "Tantalum",
        "name_eu": "Tantalo",
        "symb": "Ta",
        "Z": "73",
        "A": "180,95",
        "kind": "metall",
        "nox": "+5",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Tungstè / Wolframi",
        "name_es": "Wolframio",
        "name_en": "Tungsten",
        "name_eu": "Wolframio",
        "symb": "W",
        "Z": "74",
        "A": "183,84",
        "kind": "metall",
        "nox": "+4/+5/+6",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Reni",
        "name_es": "Renio",
        "name_en": "Rhenium",
        "name_eu": "Renio",
        "symb": "Re",
        "Z": "75",
        "A": "186,21",
        "kind": "metall",
        "nox": "+4/+6/+7",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Osmi",
        "name_es": "Osmio",
        "name_en": "Osmium",
        "name_eu": "Osmio",
        "symb": "Os",
        "Z": "76",
        "A": "190,23",
        "kind": "metall",
        "nox": "+4/+6/+8",
        "order_en_nm": "",
        "apostrof": true,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Iridi",
        "name_es": "Iridio",
        "name_en": "Iridium",
        "name_eu": "Iridio",
        "symb": "Ir",
        "Z": "77",
        "A": "192,22",
        "kind": "metall",
        "nox": "+1/+3/+4",
        "order_en_nm": "",
        "apostrof": true,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Platí",
        "name_es": "Platino",
        "name_en": "Platinum",
        "name_eu": "Platino",
        "symb": "Pt",
        "Z": "78",
        "A": "195,08",
        "kind": "metall",
        "nox": "+2/+4",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Or",
        "name_es": "Oro",
        "name_en": "Gold",
        "name_eu": "Urre",
        "symb": "Au",
        "Z": "79",
        "A": "196,97",
        "kind": "metall",
        "nox": "+1/+3",
        "order_en_nm": "",
        "apostrof": true,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Mercuri",
        "name_es": "Mercurio",
        "name_en": "Mercury",
        "name_eu": "Merkurio",
        "symb": "Hg",
        "Z": "80",
        "A": "200,59",
        "kind": "metall",
        "nox": "+1/+2",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Tal·li",
        "name_es": "Talio",
        "name_en": "Thallium",
        "name_eu": "Talio",
        "symb": "Tl",
        "Z": "81",
        "A": "204,38",
        "kind": "metall",
        "nox": "+1/+3",
        "order_en_nm": "26",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Plom",
        "name_es": "Plomo",
        "name_en": "Lead",
        "name_eu": "Berun",
        "symb": "Pb",
        "Z": "82",
        "A": "207,2",
        "kind": "metall",
        "nox": "+2/+4",
        "order_en_nm": "21",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Bismut",
        "name_es": "Bismuto",
        "name_en": "Bismuth",
        "name_eu": "Bismuto",
        "symb": "Bi",
        "Z": "83",
        "A": "208,98",
        "kind": "metall",
        "nox": "+3/+5",
        "order_en_nm": "16",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Poloni",
        "name_es": "Polonio",
        "name_en": "Polonium",
        "name_eu": "Polonio",
        "symb": "Po",
        "Z": "84",
        "A": "-209",
        "kind": "metal·loide",
        "nox": "+2/+4",
        "order_en_nm": "10",
        "apostrof": false,
        "stem_ca": "Polon",
        "stem_es": "Polon",
        "stem_en": "Polon",
        "stem_eu": "Polon"
    },
    {
        "name_ca": "Àstat",
        "name_es": "Astato",
        "name_en": "Astatine",
        "name_eu": "Astato",
        "symb": "At",
        "Z": "85",
        "A": "-210",
        "kind": "no-metall",
        "nox": "–1/+1",
        "order_en_nm": "5",
        "apostrof": false,
        "stem_ca": "Astat",
        "stem_es": "Astat",
        "stem_en": "Astat",
        "stem_eu": "Astat"
    },
    {
        "name_ca": "Radó",
        "name_es": "Radón",
        "name_en": "Radon",
        "name_eu": "Radon",
        "symb": "Rn",
        "Z": "86",
        "A": "-222",
        "kind": "gas noble",
        "nox": "0",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Franci",
        "name_es": "Francio",
        "name_en": "Francium",
        "name_eu": "Frantzio",
        "symb": "Fr",
        "Z": "87",
        "A": "-223",
        "kind": "metall",
        "nox": "+1",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Radi",
        "name_es": "Radio",
        "name_en": "Radium",
        "name_eu": "Radio",
        "symb": "Ra",
        "Z": "88",
        "A": "-226",
        "kind": "metall",
        "nox": "+2",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Actini",
        "name_es": "Actinio",
        "name_en": "Actinium",
        "name_eu": "Aktinio",
        "symb": "Ac",
        "Z": "89",
        "A": "-227",
        "kind": "metall",
        "nox": "+3",
        "order_en_nm": "",
        "apostrof": true,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Tori",
        "name_es": "Torio",
        "name_en": "Thorium",
        "name_eu": "Torio",
        "symb": "Th",
        "Z": "90",
        "A": "232,04",
        "kind": "metall",
        "nox": "+4",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Protoactini",
        "name_es": "Protactinio",
        "name_en": "Protactinium",
        "name_eu": "Protoaktinio",
        "symb": "Pa",
        "Z": "91",
        "A": "231,04",
        "kind": "metall",
        "nox": "+3/+4/+5",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Urani",
        "name_es": "Uranio",
        "name_en": "Uranium",
        "name_eu": "Uranio",
        "symb": "U",
        "Z": "92",
        "A": "238,03",
        "kind": "metall",
        "nox": "+3/+4/+5/+6",
        "order_en_nm": "",
        "apostrof": true,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Neptuni",
        "name_es": "Neptunio",
        "name_en": "Neptunium",
        "name_eu": "Neptunio",
        "symb": "Np",
        "Z": "93",
        "A": "-237",
        "kind": "metall",
        "nox": "+3/+4/+5",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Plutoni",
        "name_es": "Plutonio",
        "name_en": "Plutonium",
        "name_eu": "Plutonio",
        "symb": "Pu",
        "Z": "94",
        "A": "-244",
        "kind": "metall",
        "nox": "+3/+4/+5/+6",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Americi",
        "name_es": "Americio",
        "name_en": "Americium",
        "name_eu": "Amerizio",
        "symb": "Am",
        "Z": "95",
        "A": "-243",
        "kind": "metall",
        "nox": "+3/+4/+5/+6",
        "order_en_nm": "",
        "apostrof": true,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Curi",
        "name_es": "Curio",
        "name_en": "Curium",
        "name_eu": "Kurio",
        "symb": "Cm",
        "Z": "96",
        "A": "-247",
        "kind": "metall",
        "nox": "+3",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Berkeli",
        "name_es": "Berkelio",
        "name_en": "Berkelium",
        "name_eu": "Berkelio",
        "symb": "Bk",
        "Z": "97",
        "A": "-247",
        "kind": "metall",
        "nox": "+3/+4",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Californi",
        "name_es": "Californio",
        "name_en": "Californium",
        "name_eu": "Kalifornio",
        "symb": "Cf",
        "Z": "98",
        "A": "-251",
        "kind": "metall",
        "nox": "+3",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Einsteini",
        "name_es": "Einstenio",
        "name_en": "Einsteinium",
        "name_eu": "Einsteinio",
        "symb": "Es",
        "Z": "99",
        "A": "-252",
        "kind": "metall",
        "nox": "+3",
        "order_en_nm": "",
        "apostrof": true,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Fermi",
        "name_es": "Fermio",
        "name_en": "Fermium",
        "name_eu": "Fermio",
        "symb": "Fm",
        "Z": "100",
        "A": "-257",
        "kind": "metall",
        "nox": "+3",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Mendelevi",
        "name_es": "Mendelevio",
        "name_en": "Mendelevium",
        "name_eu": "Mendelevio",
        "symb": "Md",
        "Z": "101",
        "A": "-258",
        "kind": "metall",
        "nox": "+3",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Nobeli",
        "name_es": "Nobelio",
        "name_en": "Nobelium",
        "name_eu": "Nobelio",
        "symb": "No",
        "Z": "102",
        "A": "-259",
        "kind": "metall",
        "nox": "+3",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Lawrenci",
        "name_es": "Lawrencio",
        "name_en": "Lawrencium",
        "name_eu": "Lawrentzio",
        "symb": "Lr",
        "Z": "103",
        "A": "-266",
        "kind": "metall",
        "nox": "+3",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Rutherfordi",
        "name_es": "Rutherfordio",
        "name_en": "Rutherfordium",
        "name_eu": "Rutherfordio",
        "symb": "Rf",
        "Z": "104",
        "A": "-267",
        "kind": "metall",
        "nox": "",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Dubni",
        "name_es": "Dubnio",
        "name_en": "Dubnium",
        "name_eu": "Dubnio",
        "symb": "Db",
        "Z": "105",
        "A": "-268",
        "kind": "metall",
        "nox": "",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Seaborgi",
        "name_es": "Seaborgio",
        "name_en": "Seaborgium",
        "name_eu": "Seaborgio",
        "symb": "Sg",
        "Z": "106",
        "A": "-269",
        "kind": "metall",
        "nox": "",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Bohri",
        "name_es": "Bohrio",
        "name_en": "Bohrium",
        "name_eu": "Bohrio",
        "symb": "Bh",
        "Z": "107",
        "A": "-278",
        "kind": "metall",
        "nox": "",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Hassi",
        "name_es": "Hasio",
        "name_en": "Hassium",
        "name_eu": "Hasio",
        "symb": "Hs",
        "Z": "108",
        "A": "-278",
        "kind": "metall",
        "nox": "",
        "order_en_nm": "",
        "apostrof": true,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Meitneri",
        "name_es": "Meitnerio",
        "name_en": "Meitnerium",
        "name_eu": "Meitnerio",
        "symb": "Mt",
        "Z": "109",
        "A": "-282",
        "kind": "metall",
        "nox": "",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Darmstadti",
        "name_es": "Darmstatio",
        "name_en": "Darmstadtium",
        "name_eu": "Darmstatio",
        "symb": "Ds",
        "Z": "110",
        "A": "-282",
        "kind": "metall",
        "nox": "",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Roentgeni",
        "name_es": "Roentgenio",
        "name_en": "Roentgenium",
        "name_eu": "Roentgenio",
        "symb": "Rg",
        "Z": "111",
        "A": "-286",
        "kind": "metall",
        "nox": "",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Copernici",
        "name_es": "Copernicio",
        "name_en": "Copernicium",
        "name_eu": "Kopernizio",
        "symb": "Cn",
        "Z": "112",
        "A": "-286",
        "kind": "metall",
        "nox": "",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Nihoni",
        "name_es": "Nihonio",
        "name_en": "Nihonium",
        "name_eu": "Nihonio",
        "symb": "Nh",
        "Z": "113",
        "A": "-286",
        "kind": "metall",
        "nox": "",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Flerovi",
        "name_es": "Flerovio",
        "name_en": "Flerovium",
        "name_eu": "Flerovio",
        "symb": "Fl",
        "Z": "114",
        "A": "-290",
        "kind": "metall",
        "nox": "",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Moscovi",
        "name_es": "Moscovio",
        "name_en": "Moscovium",
        "name_eu": "Moskovio",
        "symb": "Mc",
        "Z": "115",
        "A": "-290",
        "kind": "metall",
        "nox": "",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Livermori",
        "name_es": "Livermorio",
        "name_en": "Livermorium",
        "name_eu": "Livermorio",
        "symb": "Lv",
        "Z": "116",
        "A": "-293",
        "kind": "metall",
        "nox": "",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Tennes",
        "name_es": "Teneso",
        "name_en": "Tennessine",
        "name_eu": "Teneso",
        "symb": "Ts",
        "Z": "117",
        "A": "-294",
        "kind": "no-metall",
        "nox": "",
        "order_en_nm": "",
        "apostrof": false,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "name_ca": "Oganessó",
        "name_es": "Oganesón",
        "name_en": "Oganesson",
        "name_eu": "Oganeson",
        "symb": "Og",
        "Z": "118",
        "A": "-294",
        "kind": "gas noble",
        "nox": "",
        "order_en_nm": "",
        "apostrof": true,
        "stem_ca": "",
        "stem_es": "",
        "stem_en": "",
        "stem_eu": ""
    },
    {
        "symb": "X"
    }
];
